/**
 * generated by Xtext 2.23.0
 */
package org.bpy.score.club.tests;

import com.google.inject.Inject;
import org.bpy.score.club.club.Club;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ClubInjectorProvider.class)
@SuppressWarnings("all")
public class ClubParsingTest {
  @Inject
  private ParseHelper<Club> parseHelper;

  @Test
  public void loadModel() {
  }
}
