/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import java.util.Collection;

import org.bpy.score.game.game.Actions;
import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.GameResume;
import org.bpy.score.game.game.HalfInning;
import org.bpy.score.game.game.LineUp;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Actions</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.ActionsImpl#getLineup <em>Lineup</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.ActionsImpl#getHalfInnings <em>Half Innings</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.ActionsImpl#getGameResume <em>Game Resume</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActionsImpl extends MinimalEObjectImpl.Container implements Actions
{
  /**
   * The cached value of the '{@link #getLineup() <em>Lineup</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineup()
   * @generated
   * @ordered
   */
  protected EList<LineUp> lineup;

  /**
   * The cached value of the '{@link #getHalfInnings() <em>Half Innings</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHalfInnings()
   * @generated
   * @ordered
   */
  protected EList<HalfInning> halfInnings;

  /**
   * The cached value of the '{@link #getGameResume() <em>Game Resume</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGameResume()
   * @generated
   * @ordered
   */
  protected GameResume gameResume;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.ACTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LineUp> getLineup()
  {
    if (lineup == null)
    {
      lineup = new EObjectContainmentEList<LineUp>(LineUp.class, this, GamePackage.ACTIONS__LINEUP);
    }
    return lineup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<HalfInning> getHalfInnings()
  {
    if (halfInnings == null)
    {
      halfInnings = new EObjectContainmentEList<HalfInning>(HalfInning.class, this, GamePackage.ACTIONS__HALF_INNINGS);
    }
    return halfInnings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GameResume getGameResume()
  {
    return gameResume;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGameResume(GameResume newGameResume, NotificationChain msgs)
  {
    GameResume oldGameResume = gameResume;
    gameResume = newGameResume;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.ACTIONS__GAME_RESUME, oldGameResume, newGameResume);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGameResume(GameResume newGameResume)
  {
    if (newGameResume != gameResume)
    {
      NotificationChain msgs = null;
      if (gameResume != null)
        msgs = ((InternalEObject)gameResume).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.ACTIONS__GAME_RESUME, null, msgs);
      if (newGameResume != null)
        msgs = ((InternalEObject)newGameResume).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.ACTIONS__GAME_RESUME, null, msgs);
      msgs = basicSetGameResume(newGameResume, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.ACTIONS__GAME_RESUME, newGameResume, newGameResume));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.ACTIONS__LINEUP:
        return ((InternalEList<?>)getLineup()).basicRemove(otherEnd, msgs);
      case GamePackage.ACTIONS__HALF_INNINGS:
        return ((InternalEList<?>)getHalfInnings()).basicRemove(otherEnd, msgs);
      case GamePackage.ACTIONS__GAME_RESUME:
        return basicSetGameResume(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.ACTIONS__LINEUP:
        return getLineup();
      case GamePackage.ACTIONS__HALF_INNINGS:
        return getHalfInnings();
      case GamePackage.ACTIONS__GAME_RESUME:
        return getGameResume();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.ACTIONS__LINEUP:
        getLineup().clear();
        getLineup().addAll((Collection<? extends LineUp>)newValue);
        return;
      case GamePackage.ACTIONS__HALF_INNINGS:
        getHalfInnings().clear();
        getHalfInnings().addAll((Collection<? extends HalfInning>)newValue);
        return;
      case GamePackage.ACTIONS__GAME_RESUME:
        setGameResume((GameResume)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.ACTIONS__LINEUP:
        getLineup().clear();
        return;
      case GamePackage.ACTIONS__HALF_INNINGS:
        getHalfInnings().clear();
        return;
      case GamePackage.ACTIONS__GAME_RESUME:
        setGameResume((GameResume)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.ACTIONS__LINEUP:
        return lineup != null && !lineup.isEmpty();
      case GamePackage.ACTIONS__HALF_INNINGS:
        return halfInnings != null && !halfInnings.isEmpty();
      case GamePackage.ACTIONS__GAME_RESUME:
        return gameResume != null;
    }
    return super.eIsSet(featureID);
  }

} //ActionsImpl
