/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.AdvanceWithContinuation;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Advance With Continuation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AdvanceWithContinuationImpl extends MinimalEObjectImpl.Container implements AdvanceWithContinuation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AdvanceWithContinuationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.ADVANCE_WITH_CONTINUATION;
  }

} //AdvanceWithContinuationImpl
