/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterAdvanceOnTripleHit;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Advance On Triple Hit</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BatterAdvanceOnTripleHitImpl extends HitImpl implements BatterAdvanceOnTripleHit
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterAdvanceOnTripleHitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_ADVANCE_ON_TRIPLE_HIT;
  }

} //BatterAdvanceOnTripleHitImpl
