/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterBalk;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Balk</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.BatterBalkImpl#getBatterAction <em>Batter Action</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BatterBalkImpl extends BatterActionImpl implements BatterBalk
{
  /**
   * The default value of the '{@link #getBatterAction() <em>Batter Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatterAction()
   * @generated
   * @ordered
   */
  protected static final String BATTER_ACTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBatterAction() <em>Batter Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatterAction()
   * @generated
   * @ordered
   */
  protected String batterAction = BATTER_ACTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterBalkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_BALK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBatterAction()
  {
    return batterAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBatterAction(String newBatterAction)
  {
    String oldBatterAction = batterAction;
    batterAction = newBatterAction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.BATTER_BALK__BATTER_ACTION, oldBatterAction, batterAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.BATTER_BALK__BATTER_ACTION:
        return getBatterAction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.BATTER_BALK__BATTER_ACTION:
        setBatterAction((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.BATTER_BALK__BATTER_ACTION:
        setBatterAction(BATTER_ACTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.BATTER_BALK__BATTER_ACTION:
        return BATTER_ACTION_EDEFAULT == null ? batterAction != null : !BATTER_ACTION_EDEFAULT.equals(batterAction);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (batterAction: ");
    result.append(batterAction);
    result.append(')');
    return result.toString();
  }

} //BatterBalkImpl
