/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterAdvanceOnKAbr;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Advance On KAbr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BatterAdvanceOnKAbrImpl extends OtherBatterAdvanceImpl implements BatterAdvanceOnKAbr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterAdvanceOnKAbrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_ADVANCE_ON_KABR;
  }

} //BatterAdvanceOnKAbrImpl
