/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterAdvanceOnSacrificeFlyWithError;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Advance On Sacrifice Fly With Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BatterAdvanceOnSacrificeFlyWithErrorImpl extends OtherBatterAdvanceImpl implements BatterAdvanceOnSacrificeFlyWithError
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterAdvanceOnSacrificeFlyWithErrorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_ADVANCE_ON_SACRIFICE_FLY_WITH_ERROR;
  }

} //BatterAdvanceOnSacrificeFlyWithErrorImpl
