/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterAdvanceOnReceiveError;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Advance On Receive Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BatterAdvanceOnReceiveErrorImpl extends DecisiveErrorImpl implements BatterAdvanceOnReceiveError
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterAdvanceOnReceiveErrorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_ADVANCE_ON_RECEIVE_ERROR;
  }

} //BatterAdvanceOnReceiveErrorImpl
