/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterOutOnReleasedStrike;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Out On Released Strike</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BatterOutOnReleasedStrikeImpl extends StrikeOutImpl implements BatterOutOnReleasedStrike
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterOutOnReleasedStrikeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_OUT_ON_RELEASED_STRIKE;
  }

} //BatterOutOnReleasedStrikeImpl
