/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.BatterAdvanceOnIntentionalBaseOnBall;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Batter Advance On Intentional Base On Ball</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BatterAdvanceOnIntentionalBaseOnBallImpl extends OtherBatterAdvanceImpl implements BatterAdvanceOnIntentionalBaseOnBall
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BatterAdvanceOnIntentionalBaseOnBallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.BATTER_ADVANCE_ON_INTENTIONAL_BASE_ON_BALL;
  }

} //BatterAdvanceOnIntentionalBaseOnBallImpl
