/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.DefensiveChoiceForBatter;
import org.bpy.score.game.game.GamePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Defensive Choice For Batter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.DefensiveChoiceForBatterImpl#getBatterAdvance <em>Batter Advance</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefensiveChoiceForBatterImpl extends BatterAdvanceImpl implements DefensiveChoiceForBatter
{
  /**
   * The default value of the '{@link #getBatterAdvance() <em>Batter Advance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatterAdvance()
   * @generated
   * @ordered
   */
  protected static final String BATTER_ADVANCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBatterAdvance() <em>Batter Advance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatterAdvance()
   * @generated
   * @ordered
   */
  protected String batterAdvance = BATTER_ADVANCE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefensiveChoiceForBatterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.DEFENSIVE_CHOICE_FOR_BATTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBatterAdvance()
  {
    return batterAdvance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBatterAdvance(String newBatterAdvance)
  {
    String oldBatterAdvance = batterAdvance;
    batterAdvance = newBatterAdvance;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.DEFENSIVE_CHOICE_FOR_BATTER__BATTER_ADVANCE, oldBatterAdvance, batterAdvance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.DEFENSIVE_CHOICE_FOR_BATTER__BATTER_ADVANCE:
        return getBatterAdvance();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.DEFENSIVE_CHOICE_FOR_BATTER__BATTER_ADVANCE:
        setBatterAdvance((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.DEFENSIVE_CHOICE_FOR_BATTER__BATTER_ADVANCE:
        setBatterAdvance(BATTER_ADVANCE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.DEFENSIVE_CHOICE_FOR_BATTER__BATTER_ADVANCE:
        return BATTER_ADVANCE_EDEFAULT == null ? batterAdvance != null : !BATTER_ADVANCE_EDEFAULT.equals(batterAdvance);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (batterAdvance: ");
    result.append(batterAdvance);
    result.append(')');
    return result.toString();
  }

} //DefensiveChoiceForBatterImpl
