/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.GameResume;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resume</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.GameResumeImpl#getWin <em>Win</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.GameResumeImpl#getLose <em>Lose</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.GameResumeImpl#getSave <em>Save</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GameResumeImpl extends MinimalEObjectImpl.Container implements GameResume
{
  /**
   * The default value of the '{@link #getWin() <em>Win</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWin()
   * @generated
   * @ordered
   */
  protected static final String WIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWin() <em>Win</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWin()
   * @generated
   * @ordered
   */
  protected String win = WIN_EDEFAULT;

  /**
   * The default value of the '{@link #getLose() <em>Lose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLose()
   * @generated
   * @ordered
   */
  protected static final String LOSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLose() <em>Lose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLose()
   * @generated
   * @ordered
   */
  protected String lose = LOSE_EDEFAULT;

  /**
   * The default value of the '{@link #getSave() <em>Save</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSave()
   * @generated
   * @ordered
   */
  protected static final String SAVE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSave() <em>Save</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSave()
   * @generated
   * @ordered
   */
  protected String save = SAVE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GameResumeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.GAME_RESUME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWin()
  {
    return win;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWin(String newWin)
  {
    String oldWin = win;
    win = newWin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.GAME_RESUME__WIN, oldWin, win));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLose()
  {
    return lose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLose(String newLose)
  {
    String oldLose = lose;
    lose = newLose;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.GAME_RESUME__LOSE, oldLose, lose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSave()
  {
    return save;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSave(String newSave)
  {
    String oldSave = save;
    save = newSave;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.GAME_RESUME__SAVE, oldSave, save));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.GAME_RESUME__WIN:
        return getWin();
      case GamePackage.GAME_RESUME__LOSE:
        return getLose();
      case GamePackage.GAME_RESUME__SAVE:
        return getSave();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.GAME_RESUME__WIN:
        setWin((String)newValue);
        return;
      case GamePackage.GAME_RESUME__LOSE:
        setLose((String)newValue);
        return;
      case GamePackage.GAME_RESUME__SAVE:
        setSave((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.GAME_RESUME__WIN:
        setWin(WIN_EDEFAULT);
        return;
      case GamePackage.GAME_RESUME__LOSE:
        setLose(LOSE_EDEFAULT);
        return;
      case GamePackage.GAME_RESUME__SAVE:
        setSave(SAVE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.GAME_RESUME__WIN:
        return WIN_EDEFAULT == null ? win != null : !WIN_EDEFAULT.equals(win);
      case GamePackage.GAME_RESUME__LOSE:
        return LOSE_EDEFAULT == null ? lose != null : !LOSE_EDEFAULT.equals(lose);
      case GamePackage.GAME_RESUME__SAVE:
        return SAVE_EDEFAULT == null ? save != null : !SAVE_EDEFAULT.equals(save);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (win: ");
    result.append(win);
    result.append(", lose: ");
    result.append(lose);
    result.append(", save: ");
    result.append(save);
    result.append(')');
    return result.toString();
  }

} //GameResumeImpl
