/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.InningSetting;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inning Setting</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.InningSettingImpl#isIsTiebrak <em>Is Tiebrak</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InningSettingImpl extends MinimalEObjectImpl.Container implements InningSetting
{
  /**
   * The default value of the '{@link #isIsTiebrak() <em>Is Tiebrak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsTiebrak()
   * @generated
   * @ordered
   */
  protected static final boolean IS_TIEBRAK_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsTiebrak() <em>Is Tiebrak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsTiebrak()
   * @generated
   * @ordered
   */
  protected boolean isTiebrak = IS_TIEBRAK_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InningSettingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.INNING_SETTING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsTiebrak()
  {
    return isTiebrak;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsTiebrak(boolean newIsTiebrak)
  {
    boolean oldIsTiebrak = isTiebrak;
    isTiebrak = newIsTiebrak;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.INNING_SETTING__IS_TIEBRAK, oldIsTiebrak, isTiebrak));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.INNING_SETTING__IS_TIEBRAK:
        return isIsTiebrak();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.INNING_SETTING__IS_TIEBRAK:
        setIsTiebrak((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.INNING_SETTING__IS_TIEBRAK:
        setIsTiebrak(IS_TIEBRAK_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.INNING_SETTING__IS_TIEBRAK:
        return isTiebrak != IS_TIEBRAK_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isTiebrak: ");
    result.append(isTiebrak);
    result.append(')');
    return result.toString();
  }

} //InningSettingImpl
