/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.LineUpEntry;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Line Up Entry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.LineUpEntryImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.LineUpEntryImpl#getDefensivePosition <em>Defensive Position</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.LineUpEntryImpl#getShirtNumber <em>Shirt Number</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.LineUpEntryImpl#getLaterality <em>Laterality</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LineUpEntryImpl extends MinimalEObjectImpl.Container implements LineUpEntry
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDefensivePosition() <em>Defensive Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefensivePosition()
   * @generated
   * @ordered
   */
  protected static final String DEFENSIVE_POSITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefensivePosition() <em>Defensive Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefensivePosition()
   * @generated
   * @ordered
   */
  protected String defensivePosition = DEFENSIVE_POSITION_EDEFAULT;

  /**
   * The default value of the '{@link #getShirtNumber() <em>Shirt Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShirtNumber()
   * @generated
   * @ordered
   */
  protected static final int SHIRT_NUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getShirtNumber() <em>Shirt Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShirtNumber()
   * @generated
   * @ordered
   */
  protected int shirtNumber = SHIRT_NUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getLaterality() <em>Laterality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLaterality()
   * @generated
   * @ordered
   */
  protected static final String LATERALITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLaterality() <em>Laterality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLaterality()
   * @generated
   * @ordered
   */
  protected String laterality = LATERALITY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LineUpEntryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.LINE_UP_ENTRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LINE_UP_ENTRY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefensivePosition()
  {
    return defensivePosition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefensivePosition(String newDefensivePosition)
  {
    String oldDefensivePosition = defensivePosition;
    defensivePosition = newDefensivePosition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LINE_UP_ENTRY__DEFENSIVE_POSITION, oldDefensivePosition, defensivePosition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getShirtNumber()
  {
    return shirtNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShirtNumber(int newShirtNumber)
  {
    int oldShirtNumber = shirtNumber;
    shirtNumber = newShirtNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LINE_UP_ENTRY__SHIRT_NUMBER, oldShirtNumber, shirtNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLaterality()
  {
    return laterality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLaterality(String newLaterality)
  {
    String oldLaterality = laterality;
    laterality = newLaterality;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LINE_UP_ENTRY__LATERALITY, oldLaterality, laterality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP_ENTRY__NAME:
        return getName();
      case GamePackage.LINE_UP_ENTRY__DEFENSIVE_POSITION:
        return getDefensivePosition();
      case GamePackage.LINE_UP_ENTRY__SHIRT_NUMBER:
        return getShirtNumber();
      case GamePackage.LINE_UP_ENTRY__LATERALITY:
        return getLaterality();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP_ENTRY__NAME:
        setName((String)newValue);
        return;
      case GamePackage.LINE_UP_ENTRY__DEFENSIVE_POSITION:
        setDefensivePosition((String)newValue);
        return;
      case GamePackage.LINE_UP_ENTRY__SHIRT_NUMBER:
        setShirtNumber((Integer)newValue);
        return;
      case GamePackage.LINE_UP_ENTRY__LATERALITY:
        setLaterality((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP_ENTRY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GamePackage.LINE_UP_ENTRY__DEFENSIVE_POSITION:
        setDefensivePosition(DEFENSIVE_POSITION_EDEFAULT);
        return;
      case GamePackage.LINE_UP_ENTRY__SHIRT_NUMBER:
        setShirtNumber(SHIRT_NUMBER_EDEFAULT);
        return;
      case GamePackage.LINE_UP_ENTRY__LATERALITY:
        setLaterality(LATERALITY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP_ENTRY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GamePackage.LINE_UP_ENTRY__DEFENSIVE_POSITION:
        return DEFENSIVE_POSITION_EDEFAULT == null ? defensivePosition != null : !DEFENSIVE_POSITION_EDEFAULT.equals(defensivePosition);
      case GamePackage.LINE_UP_ENTRY__SHIRT_NUMBER:
        return shirtNumber != SHIRT_NUMBER_EDEFAULT;
      case GamePackage.LINE_UP_ENTRY__LATERALITY:
        return LATERALITY_EDEFAULT == null ? laterality != null : !LATERALITY_EDEFAULT.equals(laterality);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", defensivePosition: ");
    result.append(defensivePosition);
    result.append(", shirtNumber: ");
    result.append(shirtNumber);
    result.append(", laterality: ");
    result.append(laterality);
    result.append(')');
    return result.toString();
  }

} //LineUpEntryImpl
