/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import java.util.Collection;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.LineUp;
import org.bpy.score.game.game.LineUpEntry;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Line Up</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.LineUpImpl#getTeamType <em>Team Type</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.LineUpImpl#getLineUpEntries <em>Line Up Entries</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LineUpImpl extends MinimalEObjectImpl.Container implements LineUp
{
  /**
   * The default value of the '{@link #getTeamType() <em>Team Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeamType()
   * @generated
   * @ordered
   */
  protected static final String TEAM_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTeamType() <em>Team Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeamType()
   * @generated
   * @ordered
   */
  protected String teamType = TEAM_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getLineUpEntries() <em>Line Up Entries</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineUpEntries()
   * @generated
   * @ordered
   */
  protected EList<LineUpEntry> lineUpEntries;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LineUpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.LINE_UP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTeamType()
  {
    return teamType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTeamType(String newTeamType)
  {
    String oldTeamType = teamType;
    teamType = newTeamType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LINE_UP__TEAM_TYPE, oldTeamType, teamType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LineUpEntry> getLineUpEntries()
  {
    if (lineUpEntries == null)
    {
      lineUpEntries = new EObjectContainmentEList<LineUpEntry>(LineUpEntry.class, this, GamePackage.LINE_UP__LINE_UP_ENTRIES);
    }
    return lineUpEntries;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP__LINE_UP_ENTRIES:
        return ((InternalEList<?>)getLineUpEntries()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP__TEAM_TYPE:
        return getTeamType();
      case GamePackage.LINE_UP__LINE_UP_ENTRIES:
        return getLineUpEntries();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP__TEAM_TYPE:
        setTeamType((String)newValue);
        return;
      case GamePackage.LINE_UP__LINE_UP_ENTRIES:
        getLineUpEntries().clear();
        getLineUpEntries().addAll((Collection<? extends LineUpEntry>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP__TEAM_TYPE:
        setTeamType(TEAM_TYPE_EDEFAULT);
        return;
      case GamePackage.LINE_UP__LINE_UP_ENTRIES:
        getLineUpEntries().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.LINE_UP__TEAM_TYPE:
        return TEAM_TYPE_EDEFAULT == null ? teamType != null : !TEAM_TYPE_EDEFAULT.equals(teamType);
      case GamePackage.LINE_UP__LINE_UP_ENTRIES:
        return lineUpEntries != null && !lineUpEntries.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (teamType: ");
    result.append(teamType);
    result.append(')');
    return result.toString();
  }

} //LineUpImpl
