/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import java.util.Collection;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.Notes;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Notes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.NotesImpl#getNotes <em>Notes</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.NotesImpl#getNotess <em>Notess</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NotesImpl extends MinimalEObjectImpl.Container implements Notes
{
  /**
   * The cached value of the '{@link #getNotes() <em>Notes</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotes()
   * @generated
   * @ordered
   */
  protected EList<String> notes;

  /**
   * The cached value of the '{@link #getNotess() <em>Notess</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotess()
   * @generated
   * @ordered
   */
  protected EList<String> notess;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NotesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.NOTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getNotes()
  {
    if (notes == null)
    {
      notes = new EDataTypeEList<String>(String.class, this, GamePackage.NOTES__NOTES);
    }
    return notes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getNotess()
  {
    if (notess == null)
    {
      notess = new EDataTypeEList<String>(String.class, this, GamePackage.NOTES__NOTESS);
    }
    return notess;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.NOTES__NOTES:
        return getNotes();
      case GamePackage.NOTES__NOTESS:
        return getNotess();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.NOTES__NOTES:
        getNotes().clear();
        getNotes().addAll((Collection<? extends String>)newValue);
        return;
      case GamePackage.NOTES__NOTESS:
        getNotess().clear();
        getNotess().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.NOTES__NOTES:
        getNotes().clear();
        return;
      case GamePackage.NOTES__NOTESS:
        getNotess().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.NOTES__NOTES:
        return notes != null && !notes.isEmpty();
      case GamePackage.NOTES__NOTESS:
        return notess != null && !notess.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (notes: ");
    result.append(notes);
    result.append(", notess: ");
    result.append(notess);
    result.append(')');
    return result.toString();
  }

} //NotesImpl
