/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerAdvanceOnNoDecisiveObstruction;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Advance On No Decisive Obstruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RunnerAdvanceOnNoDecisiveObstructionImpl extends RunnerAdvanceImpl implements RunnerAdvanceOnNoDecisiveObstruction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerAdvanceOnNoDecisiveObstructionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_ADVANCE_ON_NO_DECISIVE_OBSTRUCTION;
  }

} //RunnerAdvanceOnNoDecisiveObstructionImpl
