/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerDontAdvanceOnReceiveError;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Dont Advance On Receive Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RunnerDontAdvanceOnReceiveErrorImpl extends OtherRunnerActionImpl implements RunnerDontAdvanceOnReceiveError
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerDontAdvanceOnReceiveErrorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_DONT_ADVANCE_ON_RECEIVE_ERROR;
  }

} //RunnerDontAdvanceOnReceiveErrorImpl
