/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerAdvanceOnStolenBase;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Advance On Stolen Base</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RunnerAdvanceOnStolenBaseImpl extends RunnerAdvanceImpl implements RunnerAdvanceOnStolenBase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerAdvanceOnStolenBaseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_ADVANCE_ON_STOLEN_BASE;
  }

} //RunnerAdvanceOnStolenBaseImpl
