/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.CurrentRunner;
import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerAction;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.RunnerActionImpl#getRunner <em>Runner</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RunnerActionImpl extends MinimalEObjectImpl.Container implements RunnerAction
{
  /**
   * The cached value of the '{@link #getRunner() <em>Runner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRunner()
   * @generated
   * @ordered
   */
  protected CurrentRunner runner;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CurrentRunner getRunner()
  {
    return runner;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRunner(CurrentRunner newRunner, NotificationChain msgs)
  {
    CurrentRunner oldRunner = runner;
    runner = newRunner;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.RUNNER_ACTION__RUNNER, oldRunner, newRunner);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRunner(CurrentRunner newRunner)
  {
    if (newRunner != runner)
    {
      NotificationChain msgs = null;
      if (runner != null)
        msgs = ((InternalEObject)runner).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.RUNNER_ACTION__RUNNER, null, msgs);
      if (newRunner != null)
        msgs = ((InternalEObject)newRunner).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.RUNNER_ACTION__RUNNER, null, msgs);
      msgs = basicSetRunner(newRunner, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.RUNNER_ACTION__RUNNER, newRunner, newRunner));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ACTION__RUNNER:
        return basicSetRunner(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ACTION__RUNNER:
        return getRunner();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ACTION__RUNNER:
        setRunner((CurrentRunner)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ACTION__RUNNER:
        setRunner((CurrentRunner)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ACTION__RUNNER:
        return runner != null;
    }
    return super.eIsSet(featureID);
  }

} //RunnerActionImpl
