/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerOutOnFielderAction;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Out On Fielder Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.RunnerOutOnFielderActionImpl#getRunnerOut <em>Runner Out</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RunnerOutOnFielderActionImpl extends RunnerOutImpl implements RunnerOutOnFielderAction
{
  /**
   * The default value of the '{@link #getRunnerOut() <em>Runner Out</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRunnerOut()
   * @generated
   * @ordered
   */
  protected static final int RUNNER_OUT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRunnerOut() <em>Runner Out</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRunnerOut()
   * @generated
   * @ordered
   */
  protected int runnerOut = RUNNER_OUT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerOutOnFielderActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_OUT_ON_FIELDER_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRunnerOut()
  {
    return runnerOut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRunnerOut(int newRunnerOut)
  {
    int oldRunnerOut = runnerOut;
    runnerOut = newRunnerOut;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.RUNNER_OUT_ON_FIELDER_ACTION__RUNNER_OUT, oldRunnerOut, runnerOut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_OUT_ON_FIELDER_ACTION__RUNNER_OUT:
        return getRunnerOut();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_OUT_ON_FIELDER_ACTION__RUNNER_OUT:
        setRunnerOut((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_OUT_ON_FIELDER_ACTION__RUNNER_OUT:
        setRunnerOut(RUNNER_OUT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_OUT_ON_FIELDER_ACTION__RUNNER_OUT:
        return runnerOut != RUNNER_OUT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (runnerOut: ");
    result.append(runnerOut);
    result.append(')');
    return result.toString();
  }

} //RunnerOutOnFielderActionImpl
