/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerAdvanceOnThrowError;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Advance On Throw Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RunnerAdvanceOnThrowErrorImpl extends RunnerAdvanceImpl implements RunnerAdvanceOnThrowError
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerAdvanceOnThrowErrorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_ADVANCE_ON_THROW_ERROR;
  }

} //RunnerAdvanceOnThrowErrorImpl
