/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerAdvanceOnDefensiveChoice;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Advance On Defensive Choice</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.RunnerAdvanceOnDefensiveChoiceImpl#getRunnerAdvance <em>Runner Advance</em>}</li>
 *   <li>{@link org.bpy.score.game.game.impl.RunnerAdvanceOnDefensiveChoiceImpl#getIsEarned <em>Is Earned</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RunnerAdvanceOnDefensiveChoiceImpl extends AdvanceWithContinuationImpl implements RunnerAdvanceOnDefensiveChoice
{
  /**
   * The default value of the '{@link #getRunnerAdvance() <em>Runner Advance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRunnerAdvance()
   * @generated
   * @ordered
   */
  protected static final String RUNNER_ADVANCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRunnerAdvance() <em>Runner Advance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRunnerAdvance()
   * @generated
   * @ordered
   */
  protected String runnerAdvance = RUNNER_ADVANCE_EDEFAULT;

  /**
   * The default value of the '{@link #getIsEarned() <em>Is Earned</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIsEarned()
   * @generated
   * @ordered
   */
  protected static final String IS_EARNED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIsEarned() <em>Is Earned</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIsEarned()
   * @generated
   * @ordered
   */
  protected String isEarned = IS_EARNED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerAdvanceOnDefensiveChoiceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRunnerAdvance()
  {
    return runnerAdvance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRunnerAdvance(String newRunnerAdvance)
  {
    String oldRunnerAdvance = runnerAdvance;
    runnerAdvance = newRunnerAdvance;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__RUNNER_ADVANCE, oldRunnerAdvance, runnerAdvance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIsEarned()
  {
    return isEarned;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsEarned(String newIsEarned)
  {
    String oldIsEarned = isEarned;
    isEarned = newIsEarned;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__IS_EARNED, oldIsEarned, isEarned));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__RUNNER_ADVANCE:
        return getRunnerAdvance();
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__IS_EARNED:
        return getIsEarned();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__RUNNER_ADVANCE:
        setRunnerAdvance((String)newValue);
        return;
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__IS_EARNED:
        setIsEarned((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__RUNNER_ADVANCE:
        setRunnerAdvance(RUNNER_ADVANCE_EDEFAULT);
        return;
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__IS_EARNED:
        setIsEarned(IS_EARNED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__RUNNER_ADVANCE:
        return RUNNER_ADVANCE_EDEFAULT == null ? runnerAdvance != null : !RUNNER_ADVANCE_EDEFAULT.equals(runnerAdvance);
      case GamePackage.RUNNER_ADVANCE_ON_DEFENSIVE_CHOICE__IS_EARNED:
        return IS_EARNED_EDEFAULT == null ? isEarned != null : !IS_EARNED_EDEFAULT.equals(isEarned);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (runnerAdvance: ");
    result.append(runnerAdvance);
    result.append(", isEarned: ");
    result.append(isEarned);
    result.append(')');
    return result.toString();
  }

} //RunnerAdvanceOnDefensiveChoiceImpl
