/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerDontAdvanceOnCaughtStealingWithError;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Dont Advance On Caught Stealing With Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RunnerDontAdvanceOnCaughtStealingWithErrorImpl extends OtherRunnerActionImpl implements RunnerDontAdvanceOnCaughtStealingWithError
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerDontAdvanceOnCaughtStealingWithErrorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_DONT_ADVANCE_ON_CAUGHT_STEALING_WITH_ERROR;
  }

} //RunnerDontAdvanceOnCaughtStealingWithErrorImpl
