/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveReceiveError;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Runner Advance On Non Decisive Receive Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RunnerAdvanceOnNonDecisiveReceiveErrorImpl extends RunnerAdvanceImpl implements RunnerAdvanceOnNonDecisiveReceiveError
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RunnerAdvanceOnNonDecisiveReceiveErrorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.RUNNER_ADVANCE_ON_NON_DECISIVE_RECEIVE_ERROR;
  }

} //RunnerAdvanceOnNonDecisiveReceiveErrorImpl
