/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.impl;

import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.game.StrikeOut;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Strike Out</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.impl.StrikeOutImpl#getStrikeOutValue <em>Strike Out Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StrikeOutImpl extends BatterOutImpl implements StrikeOut
{
  /**
   * The default value of the '{@link #getStrikeOutValue() <em>Strike Out Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrikeOutValue()
   * @generated
   * @ordered
   */
  protected static final String STRIKE_OUT_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStrikeOutValue() <em>Strike Out Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrikeOutValue()
   * @generated
   * @ordered
   */
  protected String strikeOutValue = STRIKE_OUT_VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StrikeOutImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.STRIKE_OUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStrikeOutValue()
  {
    return strikeOutValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStrikeOutValue(String newStrikeOutValue)
  {
    String oldStrikeOutValue = strikeOutValue;
    strikeOutValue = newStrikeOutValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.STRIKE_OUT__STRIKE_OUT_VALUE, oldStrikeOutValue, strikeOutValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.STRIKE_OUT__STRIKE_OUT_VALUE:
        return getStrikeOutValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.STRIKE_OUT__STRIKE_OUT_VALUE:
        setStrikeOutValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.STRIKE_OUT__STRIKE_OUT_VALUE:
        setStrikeOutValue(STRIKE_OUT_VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.STRIKE_OUT__STRIKE_OUT_VALUE:
        return STRIKE_OUT_VALUE_EDEFAULT == null ? strikeOutValue != null : !STRIKE_OUT_VALUE_EDEFAULT.equals(strikeOutValue);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (strikeOutValue: ");
    result.append(strikeOutValue);
    result.append(')');
    return result.toString();
  }

} //StrikeOutImpl
