/*
 * generated by Xtext 2.28.0
 */
package org.bpy.score.club.ui.tests;

import com.google.inject.Injector;
import org.bpy.score.club.ui.internal.ClubActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ClubUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ClubActivator.getInstance().getInjector("org.bpy.score.club.Club");
	}

}
