/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.Actions#getLineup <em>Lineup</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Actions#getHalfInnings <em>Half Innings</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Actions#getGameResume <em>Game Resume</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getActions()
 * @model
 * @generated
 */
public interface Actions extends EObject
{
  /**
   * Returns the value of the '<em><b>Lineup</b></em>' containment reference list.
   * The list contents are of type {@link org.bpy.score.game.game.LineUp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lineup</em>' containment reference list.
   * @see org.bpy.score.game.game.GamePackage#getActions_Lineup()
   * @model containment="true"
   * @generated
   */
  EList<LineUp> getLineup();

  /**
   * Returns the value of the '<em><b>Half Innings</b></em>' containment reference list.
   * The list contents are of type {@link org.bpy.score.game.game.HalfInning}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Half Innings</em>' containment reference list.
   * @see org.bpy.score.game.game.GamePackage#getActions_HalfInnings()
   * @model containment="true"
   * @generated
   */
  EList<HalfInning> getHalfInnings();

  /**
   * Returns the value of the '<em><b>Game Resume</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Game Resume</em>' containment reference.
   * @see #setGameResume(GameResume)
   * @see org.bpy.score.game.game.GamePackage#getActions_GameResume()
   * @model containment="true"
   * @generated
   */
  GameResume getGameResume();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Actions#getGameResume <em>Game Resume</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Game Resume</em>' containment reference.
   * @see #getGameResume()
   * @generated
   */
  void setGameResume(GameResume value);

} // Actions
