/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Advance On Defensive Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterAdvanceOnDefensiveChoice()
 * @model
 * @generated
 */
public interface BatterAdvanceOnDefensiveChoice extends DefensiveChoiceForBatter
{
} // BatterAdvanceOnDefensiveChoice
