/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Advance On Pop Error</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterAdvanceOnPopError()
 * @model
 * @generated
 */
public interface BatterAdvanceOnPopError extends DecisiveError
{
} // BatterAdvanceOnPopError
