/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Out On Flyed</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.BatterOutOnFlyed#getBatterOut <em>Batter Out</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterOutOnFlyed()
 * @model
 * @generated
 */
public interface BatterOutOnFlyed extends FielderOut
{
  /**
   * Returns the value of the '<em><b>Batter Out</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batter Out</em>' attribute.
   * @see #setBatterOut(String)
   * @see org.bpy.score.game.game.GamePackage#getBatterOutOnFlyed_BatterOut()
   * @model
   * @generated
   */
  String getBatterOut();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.BatterOutOnFlyed#getBatterOut <em>Batter Out</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batter Out</em>' attribute.
   * @see #getBatterOut()
   * @generated
   */
  void setBatterOut(String value);

} // BatterOutOnFlyed
