/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.BatterAction#getCurrentBatter <em>Current Batter</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterAction()
 * @model
 * @generated
 */
public interface BatterAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Current Batter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current Batter</em>' containment reference.
   * @see #setCurrentBatter(CurrentBatter)
   * @see org.bpy.score.game.game.GamePackage#getBatterAction_CurrentBatter()
   * @model containment="true"
   * @generated
   */
  CurrentBatter getCurrentBatter();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.BatterAction#getCurrentBatter <em>Current Batter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current Batter</em>' containment reference.
   * @see #getCurrentBatter()
   * @generated
   */
  void setCurrentBatter(CurrentBatter value);

} // BatterAction
