/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Advance On Gdp With Error</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterAdvanceOnGdpWithError()
 * @model
 * @generated
 */
public interface BatterAdvanceOnGdpWithError extends DecisiveError
{
} // BatterAdvanceOnGdpWithError
