/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Must Out On Fly Foul Ball</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.BatterMustOutOnFlyFoulBall#getError <em>Error</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterMustOutOnFlyFoulBall()
 * @model
 * @generated
 */
public interface BatterMustOutOnFlyFoulBall extends BatterAction
{
  /**
   * Returns the value of the '<em><b>Error</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error</em>' attribute.
   * @see #setError(String)
   * @see org.bpy.score.game.game.GamePackage#getBatterMustOutOnFlyFoulBall_Error()
   * @model
   * @generated
   */
  String getError();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.BatterMustOutOnFlyFoulBall#getError <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error</em>' attribute.
   * @see #getError()
   * @generated
   */
  void setError(String value);

} // BatterMustOutOnFlyFoulBall
