/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Batter Lost Turn</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.BatterLostTurn#getBatterAdvance <em>Batter Advance</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getBatterLostTurn()
 * @model
 * @generated
 */
public interface BatterLostTurn extends BatterAction
{
  /**
   * Returns the value of the '<em><b>Batter Advance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batter Advance</em>' attribute.
   * @see #setBatterAdvance(String)
   * @see org.bpy.score.game.game.GamePackage#getBatterLostTurn_BatterAdvance()
   * @model
   * @generated
   */
  String getBatterAdvance();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.BatterLostTurn#getBatterAdvance <em>Batter Advance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batter Advance</em>' attribute.
   * @see #getBatterAdvance()
   * @generated
   */
  void setBatterAdvance(String value);

} // BatterLostTurn
