/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Current Batter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.CurrentBatter#getBatter <em>Batter</em>}</li>
 *   <li>{@link org.bpy.score.game.game.CurrentBatter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getCurrentBatter()
 * @model
 * @generated
 */
public interface CurrentBatter extends EObject
{
  /**
   * Returns the value of the '<em><b>Batter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batter</em>' attribute.
   * @see #setBatter(String)
   * @see org.bpy.score.game.game.GamePackage#getCurrentBatter_Batter()
   * @model
   * @generated
   */
  String getBatter();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.CurrentBatter#getBatter <em>Batter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batter</em>' attribute.
   * @see #getBatter()
   * @generated
   */
  void setBatter(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.bpy.score.game.game.GamePackage#getCurrentBatter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.CurrentBatter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // CurrentBatter
