/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.Description#getTournament <em>Tournament</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getStadium <em>Stadium</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getPlace <em>Place</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getDate <em>Date</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getStartTime <em>Start Time</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getEndTime <em>End Time</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getCategory <em>Category</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getType <em>Type</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getUmpires <em>Umpires</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getScorekeepers <em>Scorekeepers</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Description#getNotes <em>Notes</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getDescription()
 * @model
 * @generated
 */
public interface Description extends EObject
{
  /**
   * Returns the value of the '<em><b>Tournament</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tournament</em>' attribute.
   * @see #setTournament(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Tournament()
   * @model
   * @generated
   */
  String getTournament();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getTournament <em>Tournament</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tournament</em>' attribute.
   * @see #getTournament()
   * @generated
   */
  void setTournament(String value);

  /**
   * Returns the value of the '<em><b>Stadium</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stadium</em>' attribute.
   * @see #setStadium(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Stadium()
   * @model
   * @generated
   */
  String getStadium();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getStadium <em>Stadium</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stadium</em>' attribute.
   * @see #getStadium()
   * @generated
   */
  void setStadium(String value);

  /**
   * Returns the value of the '<em><b>Place</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Place</em>' attribute.
   * @see #setPlace(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Place()
   * @model
   * @generated
   */
  String getPlace();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getPlace <em>Place</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Place</em>' attribute.
   * @see #getPlace()
   * @generated
   */
  void setPlace(String value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Time</em>' attribute.
   * @see #setStartTime(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_StartTime()
   * @model
   * @generated
   */
  String getStartTime();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getStartTime <em>Start Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Time</em>' attribute.
   * @see #getStartTime()
   * @generated
   */
  void setStartTime(String value);

  /**
   * Returns the value of the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Time</em>' attribute.
   * @see #setEndTime(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_EndTime()
   * @model
   * @generated
   */
  String getEndTime();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getEndTime <em>End Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Time</em>' attribute.
   * @see #getEndTime()
   * @generated
   */
  void setEndTime(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Duration()
   * @model
   * @generated
   */
  String getDuration();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(String value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' attribute.
   * @see #setCategory(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Category()
   * @model
   * @generated
   */
  String getCategory();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getCategory <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' attribute.
   * @see #getCategory()
   * @generated
   */
  void setCategory(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Umpires</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Umpires</em>' containment reference.
   * @see #setUmpires(Umpires)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Umpires()
   * @model containment="true"
   * @generated
   */
  Umpires getUmpires();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getUmpires <em>Umpires</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Umpires</em>' containment reference.
   * @see #getUmpires()
   * @generated
   */
  void setUmpires(Umpires value);

  /**
   * Returns the value of the '<em><b>Scorekeepers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scorekeepers</em>' containment reference.
   * @see #setScorekeepers(ScoreKeepers)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Scorekeepers()
   * @model containment="true"
   * @generated
   */
  ScoreKeepers getScorekeepers();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getScorekeepers <em>Scorekeepers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scorekeepers</em>' containment reference.
   * @see #getScorekeepers()
   * @generated
   */
  void setScorekeepers(ScoreKeepers value);

  /**
   * Returns the value of the '<em><b>Notes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notes</em>' containment reference.
   * @see #setNotes(Notes)
   * @see org.bpy.score.game.game.GamePackage#getDescription_Notes()
   * @model containment="true"
   * @generated
   */
  Notes getNotes();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Description#getNotes <em>Notes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notes</em>' containment reference.
   * @see #getNotes()
   * @generated
   */
  void setNotes(Notes value);

} // Description
