/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.bpy.score.game.game.GamePackage
 * @generated
 */
public interface GameFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameFactory eINSTANCE = org.bpy.score.game.game.impl.GameFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Game</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game</em>'.
   * @generated
   */
  Game createGame();

  /**
   * Returns a new object of class '<em>Forfeit Game</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Forfeit Game</em>'.
   * @generated
   */
  ForfeitGame createForfeitGame();

  /**
   * Returns a new object of class '<em>Actions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actions</em>'.
   * @generated
   */
  Actions createActions();

  /**
   * Returns a new object of class '<em>Resume</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resume</em>'.
   * @generated
   */
  GameResume createGameResume();

  /**
   * Returns a new object of class '<em>Half Inning</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Half Inning</em>'.
   * @generated
   */
  HalfInning createHalfInning();

  /**
   * Returns a new object of class '<em>Commands</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commands</em>'.
   * @generated
   */
  Commands createCommands();

  /**
   * Returns a new object of class '<em>Move Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move Command</em>'.
   * @generated
   */
  MoveCommand createMoveCommand();

  /**
   * Returns a new object of class '<em>Selected Batter Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Selected Batter Command</em>'.
   * @generated
   */
  SelectedBatterCommand createSelectedBatterCommand();

  /**
   * Returns a new object of class '<em>Note</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Note</em>'.
   * @generated
   */
  Note createNote();

  /**
   * Returns a new object of class '<em>Inning Setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inning Setting</em>'.
   * @generated
   */
  InningSetting createInningSetting();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Pitches</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pitches</em>'.
   * @generated
   */
  Pitches createPitches();

  /**
   * Returns a new object of class '<em>Pitch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pitch</em>'.
   * @generated
   */
  Pitch createPitch();

  /**
   * Returns a new object of class '<em>Runner Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Action</em>'.
   * @generated
   */
  RunnerAction createRunnerAction();

  /**
   * Returns a new object of class '<em>Other Runner Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Other Runner Action</em>'.
   * @generated
   */
  OtherRunnerAction createOtherRunnerAction();

  /**
   * Returns a new object of class '<em>Runner Out</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Out</em>'.
   * @generated
   */
  RunnerOut createRunnerOut();

  /**
   * Returns a new object of class '<em>Runner Advance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance</em>'.
   * @generated
   */
  RunnerAdvance createRunnerAdvance();

  /**
   * Returns a new object of class '<em>Substitution Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Substitution Event</em>'.
   * @generated
   */
  SubstitutionEvent createSubstitutionEvent();

  /**
   * Returns a new object of class '<em>Substitution Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Substitution Description</em>'.
   * @generated
   */
  SubstitutionDescription createSubstitutionDescription();

  /**
   * Returns a new object of class '<em>New Defensive Position</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>New Defensive Position</em>'.
   * @generated
   */
  NewDefensivePosition createNewDefensivePosition();

  /**
   * Returns a new object of class '<em>Replacement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Replacement</em>'.
   * @generated
   */
  Replacement createReplacement();

  /**
   * Returns a new object of class '<em>Batter Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Action</em>'.
   * @generated
   */
  BatterAction createBatterAction();

  /**
   * Returns a new object of class '<em>Batter Balk</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Balk</em>'.
   * @generated
   */
  BatterBalk createBatterBalk();

  /**
   * Returns a new object of class '<em>Batter Must Out On Fly Foul Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Must Out On Fly Foul Ball</em>'.
   * @generated
   */
  BatterMustOutOnFlyFoulBall createBatterMustOutOnFlyFoulBall();

  /**
   * Returns a new object of class '<em>Batter Lost Turn</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Lost Turn</em>'.
   * @generated
   */
  BatterLostTurn createBatterLostTurn();

  /**
   * Returns a new object of class '<em>Batter Advance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance</em>'.
   * @generated
   */
  BatterAdvance createBatterAdvance();

  /**
   * Returns a new object of class '<em>Defensive Choice For Batter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Defensive Choice For Batter</em>'.
   * @generated
   */
  DefensiveChoiceForBatter createDefensiveChoiceForBatter();

  /**
   * Returns a new object of class '<em>More Adance Fail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>More Adance Fail</em>'.
   * @generated
   */
  MoreAdanceFail createMoreAdanceFail();

  /**
   * Returns a new object of class '<em>Advance With Continuation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Advance With Continuation</em>'.
   * @generated
   */
  AdvanceWithContinuation createAdvanceWithContinuation();

  /**
   * Returns a new object of class '<em>Other Batter Advance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Other Batter Advance</em>'.
   * @generated
   */
  OtherBatterAdvance createOtherBatterAdvance();

  /**
   * Returns a new object of class '<em>Hit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hit</em>'.
   * @generated
   */
  Hit createHit();

  /**
   * Returns a new object of class '<em>Decisive Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decisive Error</em>'.
   * @generated
   */
  DecisiveError createDecisiveError();

  /**
   * Returns a new object of class '<em>Batter Out</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out</em>'.
   * @generated
   */
  BatterOut createBatterOut();

  /**
   * Returns a new object of class '<em>Fielder Out</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fielder Out</em>'.
   * @generated
   */
  FielderOut createFielderOut();

  /**
   * Returns a new object of class '<em>Strike Out</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strike Out</em>'.
   * @generated
   */
  StrikeOut createStrikeOut();

  /**
   * Returns a new object of class '<em>Current Batter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Batter</em>'.
   * @generated
   */
  CurrentBatter createCurrentBatter();

  /**
   * Returns a new object of class '<em>Current Runner</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Runner</em>'.
   * @generated
   */
  CurrentRunner createCurrentRunner();

  /**
   * Returns a new object of class '<em>Line Up</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Up</em>'.
   * @generated
   */
  LineUp createLineUp();

  /**
   * Returns a new object of class '<em>Line Up Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Up Entry</em>'.
   * @generated
   */
  LineUpEntry createLineUpEntry();

  /**
   * Returns a new object of class '<em>Roster</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Roster</em>'.
   * @generated
   */
  Roster createRoster();

  /**
   * Returns a new object of class '<em>Player</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Player</em>'.
   * @generated
   */
  Player createPlayer();

  /**
   * Returns a new object of class '<em>Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description</em>'.
   * @generated
   */
  Description createDescription();

  /**
   * Returns a new object of class '<em>Notes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Notes</em>'.
   * @generated
   */
  Notes createNotes();

  /**
   * Returns a new object of class '<em>Score Keepers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Score Keepers</em>'.
   * @generated
   */
  ScoreKeepers createScoreKeepers();

  /**
   * Returns a new object of class '<em>Umpires</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Umpires</em>'.
   * @generated
   */
  Umpires createUmpires();

  /**
   * Returns a new object of class '<em>Runner Must Be Out On Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Must Be Out On Error</em>'.
   * @generated
   */
  RunnerMustBeOutOnError createRunnerMustBeOutOnError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnError createRunnerDontAdvanceOnError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Pick Off With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Pick Off With Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnPickOffWithError createRunnerDontAdvanceOnPickOffWithError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Caught Stealing With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Caught Stealing With Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnCaughtStealingWithError createRunnerDontAdvanceOnCaughtStealingWithError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Throw Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Throw Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnThrowError createRunnerDontAdvanceOnThrowError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Receive Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Receive Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnReceiveError createRunnerDontAdvanceOnReceiveError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Non Decisive Throw Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Non Decisive Throw Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnNonDecisiveThrowError createRunnerDontAdvanceOnNonDecisiveThrowError();

  /**
   * Returns a new object of class '<em>Runner Dont Advance On Non Decisive Receive Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Dont Advance On Non Decisive Receive Error</em>'.
   * @generated
   */
  RunnerDontAdvanceOnNonDecisiveReceiveError createRunnerDontAdvanceOnNonDecisiveReceiveError();

  /**
   * Returns a new object of class '<em>Runner Out On Caugth Stealing</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Out On Caugth Stealing</em>'.
   * @generated
   */
  RunnerOutOnCaugthStealing createRunnerOutOnCaugthStealing();

  /**
   * Returns a new object of class '<em>Runner Out On Pick Off</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Out On Pick Off</em>'.
   * @generated
   */
  RunnerOutOnPickOff createRunnerOutOnPickOff();

  /**
   * Returns a new object of class '<em>Runner Out On Fielder Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Out On Fielder Action</em>'.
   * @generated
   */
  RunnerOutOnFielderAction createRunnerOutOnFielderAction();

  /**
   * Returns a new object of class '<em>Runner Out By Rules</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Out By Rules</em>'.
   * @generated
   */
  RunnerOutByRules createRunnerOutByRules();

  /**
   * Returns a new object of class '<em>Runner Out On Appeal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Out On Appeal</em>'.
   * @generated
   */
  RunnerOutOnAppeal createRunnerOutOnAppeal();

  /**
   * Returns a new object of class '<em>Runner Advance By Batter Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance By Batter Action</em>'.
   * @generated
   */
  RunnerAdvanceByBatterAction createRunnerAdvanceByBatterAction();

  /**
   * Returns a new object of class '<em>Runner Advance On Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Error</em>'.
   * @generated
   */
  RunnerAdvanceOnError createRunnerAdvanceOnError();

  /**
   * Returns a new object of class '<em>Runner Advance On Stolen Base</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Stolen Base</em>'.
   * @generated
   */
  RunnerAdvanceOnStolenBase createRunnerAdvanceOnStolenBase();

  /**
   * Returns a new object of class '<em>Runner Advance On Wild Pitch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Wild Pitch</em>'.
   * @generated
   */
  RunnerAdvanceOnWildPitch createRunnerAdvanceOnWildPitch();

  /**
   * Returns a new object of class '<em>Runner Advance On Pass Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Pass Ball</em>'.
   * @generated
   */
  RunnerAdvanceOnPassBall createRunnerAdvanceOnPassBall();

  /**
   * Returns a new object of class '<em>Runner Advance On Balk</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Balk</em>'.
   * @generated
   */
  RunnerAdvanceOnBalk createRunnerAdvanceOnBalk();

  /**
   * Returns a new object of class '<em>Runner Advance On Pick Off With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Pick Off With Error</em>'.
   * @generated
   */
  RunnerAdvanceOnPickOffWithError createRunnerAdvanceOnPickOffWithError();

  /**
   * Returns a new object of class '<em>Runner Advance On Caught Stealing With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Caught Stealing With Error</em>'.
   * @generated
   */
  RunnerAdvanceOnCaughtStealingWithError createRunnerAdvanceOnCaughtStealingWithError();

  /**
   * Returns a new object of class '<em>Runner Advance On Occuped Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Occuped Ball</em>'.
   * @generated
   */
  RunnerAdvanceOnOccupedBall createRunnerAdvanceOnOccupedBall();

  /**
   * Returns a new object of class '<em>Runner Advance On No Decisive Obstruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On No Decisive Obstruction</em>'.
   * @generated
   */
  RunnerAdvanceOnNoDecisiveObstruction createRunnerAdvanceOnNoDecisiveObstruction();

  /**
   * Returns a new object of class '<em>Runner Advance On Decisive Obstruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Decisive Obstruction</em>'.
   * @generated
   */
  RunnerAdvanceOnDecisiveObstruction createRunnerAdvanceOnDecisiveObstruction();

  /**
   * Returns a new object of class '<em>Runner Advance On Throw</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Throw</em>'.
   * @generated
   */
  RunnerAdvanceOnThrow createRunnerAdvanceOnThrow();

  /**
   * Returns a new object of class '<em>Runner Advance On Indiference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Indiference</em>'.
   * @generated
   */
  RunnerAdvanceOnIndiference createRunnerAdvanceOnIndiference();

  /**
   * Returns a new object of class '<em>Runner Advance On Throw Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Throw Error</em>'.
   * @generated
   */
  RunnerAdvanceOnThrowError createRunnerAdvanceOnThrowError();

  /**
   * Returns a new object of class '<em>Runner Advance On Receive Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Receive Error</em>'.
   * @generated
   */
  RunnerAdvanceOnReceiveError createRunnerAdvanceOnReceiveError();

  /**
   * Returns a new object of class '<em>Runner Advance On Non Decisive Throw Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Non Decisive Throw Error</em>'.
   * @generated
   */
  RunnerAdvanceOnNonDecisiveThrowError createRunnerAdvanceOnNonDecisiveThrowError();

  /**
   * Returns a new object of class '<em>Runner Advance On Non Decisive Receive Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Non Decisive Receive Error</em>'.
   * @generated
   */
  RunnerAdvanceOnNonDecisiveReceiveError createRunnerAdvanceOnNonDecisiveReceiveError();

  /**
   * Returns a new object of class '<em>Runner Advance On Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Rule</em>'.
   * @generated
   */
  RunnerAdvanceOnRule createRunnerAdvanceOnRule();

  /**
   * Returns a new object of class '<em>Runner Advance On Other Player Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Other Player Error</em>'.
   * @generated
   */
  RunnerAdvanceOnOtherPlayerError createRunnerAdvanceOnOtherPlayerError();

  /**
   * Returns a new object of class '<em>Runner Advance On Fielder Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Fielder Choice</em>'.
   * @generated
   */
  RunnerAdvanceOnFielderChoice createRunnerAdvanceOnFielderChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Occuped Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Occuped Ball</em>'.
   * @generated
   */
  BatterAdvanceOnOccupedBall createBatterAdvanceOnOccupedBall();

  /**
   * Returns a new object of class '<em>Batter Advance On Defensive Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Defensive Choice</em>'.
   * @generated
   */
  BatterAdvanceOnDefensiveChoice createBatterAdvanceOnDefensiveChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Indiference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Indiference</em>'.
   * @generated
   */
  BatterAdvanceOnIndiference createBatterAdvanceOnIndiference();

  /**
   * Returns a new object of class '<em>Runner Advance On Non Decisive Fly Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Non Decisive Fly Error</em>'.
   * @generated
   */
  RunnerAdvanceOnNonDecisiveFlyError createRunnerAdvanceOnNonDecisiveFlyError();

  /**
   * Returns a new object of class '<em>Runner Advance On Defensive Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runner Advance On Defensive Choice</em>'.
   * @generated
   */
  RunnerAdvanceOnDefensiveChoice createRunnerAdvanceOnDefensiveChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Base On Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Base On Ball</em>'.
   * @generated
   */
  BatterAdvanceOnBaseOnBall createBatterAdvanceOnBaseOnBall();

  /**
   * Returns a new object of class '<em>Batter Advance On Intentional Base On Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Intentional Base On Ball</em>'.
   * @generated
   */
  BatterAdvanceOnIntentionalBaseOnBall createBatterAdvanceOnIntentionalBaseOnBall();

  /**
   * Returns a new object of class '<em>Batter Advance On Hit By Pitch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Hit By Pitch</em>'.
   * @generated
   */
  BatterAdvanceOnHitByPitch createBatterAdvanceOnHitByPitch();

  /**
   * Returns a new object of class '<em>Batter Advance On KPass Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On KPass Ball</em>'.
   * @generated
   */
  BatterAdvanceOnKPassBall createBatterAdvanceOnKPassBall();

  /**
   * Returns a new object of class '<em>Batter Advance On KWild Pitch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On KWild Pitch</em>'.
   * @generated
   */
  BatterAdvanceOnKWildPitch createBatterAdvanceOnKWildPitch();

  /**
   * Returns a new object of class '<em>Batter Advance On KAbr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On KAbr</em>'.
   * @generated
   */
  BatterAdvanceOnKAbr createBatterAdvanceOnKAbr();

  /**
   * Returns a new object of class '<em>Batter Advance On KWith Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On KWith Error</em>'.
   * @generated
   */
  BatterAdvanceOnKWithError createBatterAdvanceOnKWithError();

  /**
   * Returns a new object of class '<em>Batter Advance On Sacrifice Hit With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Sacrifice Hit With Error</em>'.
   * @generated
   */
  BatterAdvanceOnSacrificeHitWithError createBatterAdvanceOnSacrificeHitWithError();

  /**
   * Returns a new object of class '<em>Batter Advance On Sacrifice Hit With Fielder Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Sacrifice Hit With Fielder Choice</em>'.
   * @generated
   */
  BatterAdvanceOnSacrificeHitWithFielderChoice createBatterAdvanceOnSacrificeHitWithFielderChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Sacrifice Fly With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Sacrifice Fly With Error</em>'.
   * @generated
   */
  BatterAdvanceOnSacrificeFlyWithError createBatterAdvanceOnSacrificeFlyWithError();

  /**
   * Returns a new object of class '<em>Batter Advance On Sacrifice Fly With Fielder Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Sacrifice Fly With Fielder Choice</em>'.
   * @generated
   */
  BatterAdvanceOnSacrificeFlyWithFielderChoice createBatterAdvanceOnSacrificeFlyWithFielderChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Catcher Interference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Catcher Interference</em>'.
   * @generated
   */
  BatterAdvanceOnCatcherInterference createBatterAdvanceOnCatcherInterference();

  /**
   * Returns a new object of class '<em>Batter Advance On Obstruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Obstruction</em>'.
   * @generated
   */
  BatterAdvanceOnObstruction createBatterAdvanceOnObstruction();

  /**
   * Returns a new object of class '<em>Batter Advance On KWith Fielder Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On KWith Fielder Choice</em>'.
   * @generated
   */
  BatterAdvanceOnKWithFielderChoice createBatterAdvanceOnKWithFielderChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Gdp With Fielder Choice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Gdp With Fielder Choice</em>'.
   * @generated
   */
  BatterAdvanceOnGdpWithFielderChoice createBatterAdvanceOnGdpWithFielderChoice();

  /**
   * Returns a new object of class '<em>Batter Advance On Single Hit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Single Hit</em>'.
   * @generated
   */
  BatterAdvanceOnSingleHit createBatterAdvanceOnSingleHit();

  /**
   * Returns a new object of class '<em>Batter Advance On Double Hit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Double Hit</em>'.
   * @generated
   */
  BatterAdvanceOnDoubleHit createBatterAdvanceOnDoubleHit();

  /**
   * Returns a new object of class '<em>Batter Advance On Triple Hit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Triple Hit</em>'.
   * @generated
   */
  BatterAdvanceOnTripleHit createBatterAdvanceOnTripleHit();

  /**
   * Returns a new object of class '<em>Batter Advance On Home Run</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Home Run</em>'.
   * @generated
   */
  BatterAdvanceOnHomeRun createBatterAdvanceOnHomeRun();

  /**
   * Returns a new object of class '<em>Batter Advance On Inside Park</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Inside Park</em>'.
   * @generated
   */
  BatterAdvanceOnInsidePark createBatterAdvanceOnInsidePark();

  /**
   * Returns a new object of class '<em>Batter Advance On Fly Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Fly Error</em>'.
   * @generated
   */
  BatterAdvanceOnFlyError createBatterAdvanceOnFlyError();

  /**
   * Returns a new object of class '<em>Batter Advance On Pop Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Pop Error</em>'.
   * @generated
   */
  BatterAdvanceOnPopError createBatterAdvanceOnPopError();

  /**
   * Returns a new object of class '<em>Batter Advance On Receive Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Receive Error</em>'.
   * @generated
   */
  BatterAdvanceOnReceiveError createBatterAdvanceOnReceiveError();

  /**
   * Returns a new object of class '<em>Batter Advance On Throw Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Throw Error</em>'.
   * @generated
   */
  BatterAdvanceOnThrowError createBatterAdvanceOnThrowError();

  /**
   * Returns a new object of class '<em>Batter Advance On Gdp With Error</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Advance On Gdp With Error</em>'.
   * @generated
   */
  BatterAdvanceOnGdpWithError createBatterAdvanceOnGdpWithError();

  /**
   * Returns a new object of class '<em>Batter Out On Flyed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Flyed</em>'.
   * @generated
   */
  BatterOutOnFlyed createBatterOutOnFlyed();

  /**
   * Returns a new object of class '<em>Batter Out On Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Line</em>'.
   * @generated
   */
  BatterOutOnLine createBatterOutOnLine();

  /**
   * Returns a new object of class '<em>Batter Out On Popped</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Popped</em>'.
   * @generated
   */
  BatterOutOnPopped createBatterOutOnPopped();

  /**
   * Returns a new object of class '<em>Batter Out On Flyed Fall Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Flyed Fall Ball</em>'.
   * @generated
   */
  BatterOutOnFlyedFallBall createBatterOutOnFlyedFallBall();

  /**
   * Returns a new object of class '<em>Batter Out On Popped Fall Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Popped Fall Ball</em>'.
   * @generated
   */
  BatterOutOnPoppedFallBall createBatterOutOnPoppedFallBall();

  /**
   * Returns a new object of class '<em>Batter Out On Line Drive Fall Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Line Drive Fall Ball</em>'.
   * @generated
   */
  BatterOutOnLineDriveFallBall createBatterOutOnLineDriveFallBall();

  /**
   * Returns a new object of class '<em>Batter Out On Grounded Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Grounded Ball</em>'.
   * @generated
   */
  BatterOutOnGroundedBall createBatterOutOnGroundedBall();

  /**
   * Returns a new object of class '<em>Batter Out By Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out By Rule</em>'.
   * @generated
   */
  BatterOutByRule createBatterOutByRule();

  /**
   * Returns a new object of class '<em>Batter Out On Appeal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Appeal</em>'.
   * @generated
   */
  BatterOutOnAppeal createBatterOutOnAppeal();

  /**
   * Returns a new object of class '<em>Batter Out On Grounded Double Play</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Grounded Double Play</em>'.
   * @generated
   */
  BatterOutOnGroundedDoublePlay createBatterOutOnGroundedDoublePlay();

  /**
   * Returns a new object of class '<em>Batter Out On Sacrifice Fly</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Sacrifice Fly</em>'.
   * @generated
   */
  BatterOutOnSacrificeFly createBatterOutOnSacrificeFly();

  /**
   * Returns a new object of class '<em>Batter Out On Sacrifice Fly Fall Ball</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Sacrifice Fly Fall Ball</em>'.
   * @generated
   */
  BatterOutOnSacrificeFlyFallBall createBatterOutOnSacrificeFlyFallBall();

  /**
   * Returns a new object of class '<em>Batter Out On Sacrifice Hit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Sacrifice Hit</em>'.
   * @generated
   */
  BatterOutOnSacrificeHit createBatterOutOnSacrificeHit();

  /**
   * Returns a new object of class '<em>Batter Out On Infield Fly</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Infield Fly</em>'.
   * @generated
   */
  BatterOutOnInfieldFly createBatterOutOnInfieldFly();

  /**
   * Returns a new object of class '<em>Batter Out On Swinged Strike</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Swinged Strike</em>'.
   * @generated
   */
  BatterOutOnSwingedStrike createBatterOutOnSwingedStrike();

  /**
   * Returns a new object of class '<em>Batter Out On Looked Strike</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Looked Strike</em>'.
   * @generated
   */
  BatterOutOnLookedStrike createBatterOutOnLookedStrike();

  /**
   * Returns a new object of class '<em>Batter Out On Released Strike</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Batter Out On Released Strike</em>'.
   * @generated
   */
  BatterOutOnReleasedStrike createBatterOutOnReleasedStrike();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GamePackage getGamePackage();

} //GameFactory
