/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.Hit#getHit <em>Hit</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getHit()
 * @model
 * @generated
 */
public interface Hit extends BatterAdvance
{
  /**
   * Returns the value of the '<em><b>Hit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hit</em>' attribute.
   * @see #setHit(String)
   * @see org.bpy.score.game.game.GamePackage#getHit_Hit()
   * @model
   * @generated
   */
  String getHit();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Hit#getHit <em>Hit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hit</em>' attribute.
   * @see #getHit()
   * @generated
   */
  void setHit(String value);

} // Hit
