/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inning Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.InningSetting#isIsTiebrak <em>Is Tiebrak</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getInningSetting()
 * @model
 * @generated
 */
public interface InningSetting extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Tiebrak</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Tiebrak</em>' attribute.
   * @see #setIsTiebrak(boolean)
   * @see org.bpy.score.game.game.GamePackage#getInningSetting_IsTiebrak()
   * @model
   * @generated
   */
  boolean isIsTiebrak();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.InningSetting#isIsTiebrak <em>Is Tiebrak</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Tiebrak</em>' attribute.
   * @see #isIsTiebrak()
   * @generated
   */
  void setIsTiebrak(boolean value);

} // InningSetting
