/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Up</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.LineUp#getTeamType <em>Team Type</em>}</li>
 *   <li>{@link org.bpy.score.game.game.LineUp#getLineUpEntries <em>Line Up Entries</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getLineUp()
 * @model
 * @generated
 */
public interface LineUp extends EObject
{
  /**
   * Returns the value of the '<em><b>Team Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Team Type</em>' attribute.
   * @see #setTeamType(String)
   * @see org.bpy.score.game.game.GamePackage#getLineUp_TeamType()
   * @model
   * @generated
   */
  String getTeamType();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.LineUp#getTeamType <em>Team Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Team Type</em>' attribute.
   * @see #getTeamType()
   * @generated
   */
  void setTeamType(String value);

  /**
   * Returns the value of the '<em><b>Line Up Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.bpy.score.game.game.LineUpEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Up Entries</em>' containment reference list.
   * @see org.bpy.score.game.game.GamePackage#getLineUp_LineUpEntries()
   * @model containment="true"
   * @generated
   */
  EList<LineUpEntry> getLineUpEntries();

} // LineUp
