/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pitches</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.Pitches#getPitches <em>Pitches</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getPitches()
 * @model
 * @generated
 */
public interface Pitches extends EObject
{
  /**
   * Returns the value of the '<em><b>Pitches</b></em>' containment reference list.
   * The list contents are of type {@link org.bpy.score.game.game.Pitch}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pitches</em>' containment reference list.
   * @see org.bpy.score.game.game.GamePackage#getPitches_Pitches()
   * @model containment="true"
   * @generated
   */
  EList<Pitch> getPitches();

} // Pitches
