/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pitch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.Pitch#getPitch <em>Pitch</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getPitch()
 * @model
 * @generated
 */
public interface Pitch extends EObject
{
  /**
   * Returns the value of the '<em><b>Pitch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pitch</em>' attribute.
   * @see #setPitch(String)
   * @see org.bpy.score.game.game.GamePackage#getPitch_Pitch()
   * @model
   * @generated
   */
  String getPitch();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Pitch#getPitch <em>Pitch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pitch</em>' attribute.
   * @see #getPitch()
   * @generated
   */
  void setPitch(String value);

} // Pitch
