/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Replacement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.Replacement#getName <em>Name</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Replacement#getShirtNumber <em>Shirt Number</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Replacement#getDefensivePosition <em>Defensive Position</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Replacement#getNewDefensivePosition <em>New Defensive Position</em>}</li>
 *   <li>{@link org.bpy.score.game.game.Replacement#getLaterality <em>Laterality</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getReplacement()
 * @model
 * @generated
 */
public interface Replacement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.bpy.score.game.game.GamePackage#getReplacement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Replacement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Shirt Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shirt Number</em>' attribute.
   * @see #setShirtNumber(int)
   * @see org.bpy.score.game.game.GamePackage#getReplacement_ShirtNumber()
   * @model
   * @generated
   */
  int getShirtNumber();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Replacement#getShirtNumber <em>Shirt Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shirt Number</em>' attribute.
   * @see #getShirtNumber()
   * @generated
   */
  void setShirtNumber(int value);

  /**
   * Returns the value of the '<em><b>Defensive Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defensive Position</em>' attribute.
   * @see #setDefensivePosition(int)
   * @see org.bpy.score.game.game.GamePackage#getReplacement_DefensivePosition()
   * @model
   * @generated
   */
  int getDefensivePosition();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Replacement#getDefensivePosition <em>Defensive Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Defensive Position</em>' attribute.
   * @see #getDefensivePosition()
   * @generated
   */
  void setDefensivePosition(int value);

  /**
   * Returns the value of the '<em><b>New Defensive Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Defensive Position</em>' attribute.
   * @see #setNewDefensivePosition(String)
   * @see org.bpy.score.game.game.GamePackage#getReplacement_NewDefensivePosition()
   * @model
   * @generated
   */
  String getNewDefensivePosition();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Replacement#getNewDefensivePosition <em>New Defensive Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Defensive Position</em>' attribute.
   * @see #getNewDefensivePosition()
   * @generated
   */
  void setNewDefensivePosition(String value);

  /**
   * Returns the value of the '<em><b>Laterality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Laterality</em>' attribute.
   * @see #setLaterality(String)
   * @see org.bpy.score.game.game.GamePackage#getReplacement_Laterality()
   * @model
   * @generated
   */
  String getLaterality();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.Replacement#getLaterality <em>Laterality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Laterality</em>' attribute.
   * @see #getLaterality()
   * @generated
   */
  void setLaterality(String value);

} // Replacement
