/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Out On Appeal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.RunnerOutOnAppeal#getRunnerOut <em>Runner Out</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerOutOnAppeal()
 * @model
 * @generated
 */
public interface RunnerOutOnAppeal extends RunnerOut, MoreAdanceFail
{
  /**
   * Returns the value of the '<em><b>Runner Out</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runner Out</em>' attribute.
   * @see #setRunnerOut(String)
   * @see org.bpy.score.game.game.GamePackage#getRunnerOutOnAppeal_RunnerOut()
   * @model
   * @generated
   */
  String getRunnerOut();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.RunnerOutOnAppeal#getRunnerOut <em>Runner Out</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runner Out</em>' attribute.
   * @see #getRunnerOut()
   * @generated
   */
  void setRunnerOut(String value);

} // RunnerOutOnAppeal
