/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Advance On Non Decisive Fly Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveFlyError#getRunnerAdvance <em>Runner Advance</em>}</li>
 *   <li>{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveFlyError#getIsEarned <em>Is Earned</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerAdvanceOnNonDecisiveFlyError()
 * @model
 * @generated
 */
public interface RunnerAdvanceOnNonDecisiveFlyError extends AdvanceWithContinuation
{
  /**
   * Returns the value of the '<em><b>Runner Advance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runner Advance</em>' attribute.
   * @see #setRunnerAdvance(String)
   * @see org.bpy.score.game.game.GamePackage#getRunnerAdvanceOnNonDecisiveFlyError_RunnerAdvance()
   * @model
   * @generated
   */
  String getRunnerAdvance();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveFlyError#getRunnerAdvance <em>Runner Advance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runner Advance</em>' attribute.
   * @see #getRunnerAdvance()
   * @generated
   */
  void setRunnerAdvance(String value);

  /**
   * Returns the value of the '<em><b>Is Earned</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Earned</em>' attribute.
   * @see #setIsEarned(String)
   * @see org.bpy.score.game.game.GamePackage#getRunnerAdvanceOnNonDecisiveFlyError_IsEarned()
   * @model
   * @generated
   */
  String getIsEarned();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveFlyError#getIsEarned <em>Is Earned</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Earned</em>' attribute.
   * @see #getIsEarned()
   * @generated
   */
  void setIsEarned(String value);

} // RunnerAdvanceOnNonDecisiveFlyError
