/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Advance On Wild Pitch</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerAdvanceOnWildPitch()
 * @model
 * @generated
 */
public interface RunnerAdvanceOnWildPitch extends RunnerAdvance, AdvanceWithContinuation
{
} // RunnerAdvanceOnWildPitch
