/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Must Be Out On Error</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerMustBeOutOnError()
 * @model
 * @generated
 */
public interface RunnerMustBeOutOnError extends OtherRunnerAction
{
} // RunnerMustBeOutOnError
