/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.RunnerAction#getRunner <em>Runner</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerAction()
 * @model
 * @generated
 */
public interface RunnerAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Runner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runner</em>' containment reference.
   * @see #setRunner(CurrentRunner)
   * @see org.bpy.score.game.game.GamePackage#getRunnerAction_Runner()
   * @model containment="true"
   * @generated
   */
  CurrentRunner getRunner();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.RunnerAction#getRunner <em>Runner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runner</em>' containment reference.
   * @see #getRunner()
   * @generated
   */
  void setRunner(CurrentRunner value);

} // RunnerAction
