/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Dont Advance On Error</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerDontAdvanceOnError()
 * @model
 * @generated
 */
public interface RunnerDontAdvanceOnError extends OtherRunnerAction
{
} // RunnerDontAdvanceOnError
