/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Runner Advance On Caught Stealing With Error</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bpy.score.game.game.GamePackage#getRunnerAdvanceOnCaughtStealingWithError()
 * @model
 * @generated
 */
public interface RunnerAdvanceOnCaughtStealingWithError extends RunnerAdvance
{
} // RunnerAdvanceOnCaughtStealingWithError
