/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Score Keepers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.ScoreKeepers#getScorekeepers <em>Scorekeepers</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getScoreKeepers()
 * @model
 * @generated
 */
public interface ScoreKeepers extends EObject
{
  /**
   * Returns the value of the '<em><b>Scorekeepers</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scorekeepers</em>' attribute list.
   * @see org.bpy.score.game.game.GamePackage#getScoreKeepers_Scorekeepers()
   * @model unique="false"
   * @generated
   */
  EList<String> getScorekeepers();

} // ScoreKeepers
