/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selected Batter Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.SelectedBatterCommand#getStarterBatter <em>Starter Batter</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getSelectedBatterCommand()
 * @model
 * @generated
 */
public interface SelectedBatterCommand extends EObject
{
  /**
   * Returns the value of the '<em><b>Starter Batter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Starter Batter</em>' attribute.
   * @see #setStarterBatter(int)
   * @see org.bpy.score.game.game.GamePackage#getSelectedBatterCommand_StarterBatter()
   * @model
   * @generated
   */
  int getStarterBatter();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.SelectedBatterCommand#getStarterBatter <em>Starter Batter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Starter Batter</em>' attribute.
   * @see #getStarterBatter()
   * @generated
   */
  void setStarterBatter(int value);

} // SelectedBatterCommand
