/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Substitution Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.game.game.SubstitutionDescription#getCurrentDefensivePosition <em>Current Defensive Position</em>}</li>
 *   <li>{@link org.bpy.score.game.game.SubstitutionDescription#getName <em>Name</em>}</li>
 *   <li>{@link org.bpy.score.game.game.SubstitutionDescription#getSubtitution <em>Subtitution</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.game.game.GamePackage#getSubstitutionDescription()
 * @model
 * @generated
 */
public interface SubstitutionDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Current Defensive Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current Defensive Position</em>' attribute.
   * @see #setCurrentDefensivePosition(String)
   * @see org.bpy.score.game.game.GamePackage#getSubstitutionDescription_CurrentDefensivePosition()
   * @model
   * @generated
   */
  String getCurrentDefensivePosition();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.SubstitutionDescription#getCurrentDefensivePosition <em>Current Defensive Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current Defensive Position</em>' attribute.
   * @see #getCurrentDefensivePosition()
   * @generated
   */
  void setCurrentDefensivePosition(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.bpy.score.game.game.GamePackage#getSubstitutionDescription_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.SubstitutionDescription#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Subtitution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subtitution</em>' containment reference.
   * @see #setSubtitution(EObject)
   * @see org.bpy.score.game.game.GamePackage#getSubstitutionDescription_Subtitution()
   * @model containment="true"
   * @generated
   */
  EObject getSubtitution();

  /**
   * Sets the value of the '{@link org.bpy.score.game.game.SubstitutionDescription#getSubtitution <em>Subtitution</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subtitution</em>' containment reference.
   * @see #getSubtitution()
   * @generated
   */
  void setSubtitution(EObject value);

} // SubstitutionDescription
