/*
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.ui;

import com.google.inject.Injector;
import org.bpy.score.game.ui.internal.GameActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GameActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GameActivator activator = GameActivator.getInstance();
		return activator != null ? activator.getInjector(GameActivator.ORG_BPY_SCORE_GAME_GAME) : null;
	}

}
