/**
 * European Scoring Tool For Baseball
 * Copyright (C) 2020  Patrick BRIAND
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * generated by Xtext 2.23.0
 */
package org.bpy.score.game.tests;

import com.google.inject.Inject;
import org.bpy.score.game.game.Action;
import org.bpy.score.game.game.BatterAction;
import org.bpy.score.game.game.BatterOutOnLookedStrike;
import org.bpy.score.game.game.BatterOutOnReleasedStrike;
import org.bpy.score.game.game.BatterOutOnSwingedStrike;
import org.bpy.score.game.game.Game;
import org.bpy.score.game.game.GamePackage;
import org.bpy.score.game.validation.BatterOutValidator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(GameInjectorProvider.class)
@SuppressWarnings("all")
public class StrikeOutChecker {
  @Inject
  @Extension
  private ParseHelper<Game> _parseHelper;

  @Inject
  @Extension
  private ValidationTestHelper validationTestHelper;

  @Test
  public void checkClassicSwingedStrikeOut() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KS }");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this.validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterOutOnSwingedStrike)) {
        checkResult = true;
      }
      Assert.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkClassicLookedStrikeOut() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KL }");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this.validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterOutOnLookedStrike)) {
        checkResult = true;
      }
      Assert.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkClassicDropperCatcherStrikeOut() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> K23 }");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this.validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterOutOnReleasedStrike)) {
        checkResult = true;
      }
      Assert.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkClassicDropperCatcherStrikeOutBadNumber1() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> K20 }");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this.validationTestHelper.assertError(parseResult, GamePackage.eINSTANCE.getBatterOutOnReleasedStrike(), 
        BatterOutValidator.INVALID_DEFENDER_NUMMBER, 
        "Bad defender number \'0\', value must be set between 1 to 9");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkClassicDropperCatcherStrikeOutBadNumber2() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> K03 }");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this.validationTestHelper.assertError(parseResult, GamePackage.eINSTANCE.getBatterOutOnReleasedStrike(), 
        BatterOutValidator.INVALID_DEFENDER_NUMMBER, 
        "Bad defender number \'0\', value must be set between 1 to 9");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
