/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.club.club.impl;

import org.bpy.score.club.club.Club;
import org.bpy.score.club.club.ClubDescription;
import org.bpy.score.club.club.ClubPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Club</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.club.club.impl.ClubImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.bpy.score.club.club.impl.ClubImpl#getClubDescription <em>Club Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClubImpl extends MinimalEObjectImpl.Container implements Club
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getClubDescription() <em>Club Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClubDescription()
   * @generated
   * @ordered
   */
  protected ClubDescription clubDescription;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClubImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ClubPackage.Literals.CLUB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClubPackage.CLUB__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClubDescription getClubDescription()
  {
    return clubDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClubDescription(ClubDescription newClubDescription, NotificationChain msgs)
  {
    ClubDescription oldClubDescription = clubDescription;
    clubDescription = newClubDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ClubPackage.CLUB__CLUB_DESCRIPTION, oldClubDescription, newClubDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClubDescription(ClubDescription newClubDescription)
  {
    if (newClubDescription != clubDescription)
    {
      NotificationChain msgs = null;
      if (clubDescription != null)
        msgs = ((InternalEObject)clubDescription).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ClubPackage.CLUB__CLUB_DESCRIPTION, null, msgs);
      if (newClubDescription != null)
        msgs = ((InternalEObject)newClubDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ClubPackage.CLUB__CLUB_DESCRIPTION, null, msgs);
      msgs = basicSetClubDescription(newClubDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClubPackage.CLUB__CLUB_DESCRIPTION, newClubDescription, newClubDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ClubPackage.CLUB__CLUB_DESCRIPTION:
        return basicSetClubDescription(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ClubPackage.CLUB__NAME:
        return getName();
      case ClubPackage.CLUB__CLUB_DESCRIPTION:
        return getClubDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ClubPackage.CLUB__NAME:
        setName((String)newValue);
        return;
      case ClubPackage.CLUB__CLUB_DESCRIPTION:
        setClubDescription((ClubDescription)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ClubPackage.CLUB__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ClubPackage.CLUB__CLUB_DESCRIPTION:
        setClubDescription((ClubDescription)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ClubPackage.CLUB__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ClubPackage.CLUB__CLUB_DESCRIPTION:
        return clubDescription != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ClubImpl
