/*
 * generated by Xtext 2.28.0
 */
package org.bpy.score.club.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractClubScopeProvider extends DelegatingScopeProvider {
}
