/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.club.club;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Members</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.club.club.Members#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.club.club.ClubPackage#getMembers()
 * @model
 * @generated
 */
public interface Members extends EObject
{
  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link org.bpy.score.club.club.Member}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see org.bpy.score.club.club.ClubPackage#getMembers_Members()
   * @model containment="true"
   * @generated
   */
  EList<Member> getMembers();

} // Members
