/**
 * generated by Xtext 2.31.0
 */
package org.bpy.score.club.club;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Official</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.score.club.club.Official#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.bpy.score.club.club.ClubPackage#getOfficial()
 * @model
 * @generated
 */
public interface Official extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Member)
   * @see org.bpy.score.club.club.ClubPackage#getOfficial_Name()
   * @model
   * @generated
   */
  Member getName();

  /**
   * Sets the value of the '{@link org.bpy.score.club.club.Official#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Member value);

} // Official
