#-----------------------------------------------------
# Menu file
#-----------------------------------------------------
rcp.menu.file=File
rcp.menu.new=New
rcp.menu.new_tournament=New tournament
rcp.menu.new_season=New season
rcp.menu.new_category=New category
rcp.menu.new_game=New game
rcp.menu.new_club=New club
rcp.menu.open_file=Open file
rcp.menu.export_as_pdf=Export as PDF file
rcp.menu.openworkspace=Open workspace
rcp.menu.import=Import
rcp.menu.export=Export
rcp.menu.quit=Quit

#-----------------------------------------------------
# Menu edit
#-----------------------------------------------------
rcp.menu.edition=Edit
rcp.menu.undo=undo
rcp.menu.redo=redo
rcp.menu.cut=cut
rcp.menu.copy=copy
rcp.menu.paste=paste
rcp.menu.delete=delete
rcp.menu.select_all=Select all

#-----------------------------------------------------
# Menu Search
#-----------------------------------------------------
rcp.menu.search=Search
rcp.menu.find_replace=Find and replace
rcp.menu.search_game_by_team=Search game for a team
rcp.menu.search_game_by_date=Search game for a date
rcp.menu.search_game_by_official=Search game for official

#-----------------------------------------------------
# Menu Reports
#-----------------------------------------------------
rcp.menu.reports=Reports
rcp.menu.generate_game_reports=Generate games reports

#-----------------------------------------------------
# Menu Window
#-----------------------------------------------------
rcp.menu.window=Window
rcp.menu.new_window=New window
rcp.menu.reset_perspective=Reset perspective
rcp.menu.save_perspectives=Save perspective
rcp.menu.restore_perspectives=Restore perspective
rcp.menu.show_views=views
rcp.menu.console=View console
rcp.menu.problems=View problems
rcp.menu.general_display=General display
rcp.menu.occupation_field=Occupation field
rcp.menu.visitor_sheet=Visitor sheet
rcp.menu.hometeeam_sheet=Hometeam sheet
rcp.menu.line_up=Line up
rcp.menu.outline=Outline
rcp.menu.preferences=Preferences
rcp.menu.perspectives=Perspectives

#-----------------------------------------------------
# Menu Help
#-----------------------------------------------------
rcp.menu.help=Help
rcp.menu.welcome=Welcome
rcp.menu.help_contents=Help contents
rcp.menuabout_this_tool=About

#-----------------------------------------------------
# View title
#-----------------------------------------------------
rcp.view.tournament_manager=Tournament manager
rcp.view.field_occupation=Field occupation
rcp.view.billboard=billboard
rcp.view.score_box=Score box
rcp.view.score_sheet=Score sheet
rcp.view.visitor_score_sheet=Visitor score sheet
rcp.view.hometeam_score_sheet=Hometeam score sheet
rcp.view.cateogry=Category
rcp.view.tournament_navigator=Tournament navigator
rcp.view.activ_lineup=Activ linup

#-----------------------------------------------------
# Specific popup menu
#-----------------------------------------------------
rcp.set_as_tournament_nature=Set as score project
rcp.unset_as_tournament_nature=Unset score project
NatureRemoveCommand.label=Unconfigure Xtext

#-----------------------------------------------------
# Specific score tool import wizard
#-----------------------------------------------------
rcp.wizard.import.tournament=Import tournament
import.catagory.scoreSheetTool=Scoring tool
rcp.wizard.import.sample=Import sample project

#-----------------------------------------------------
# Specific score tool import wizard
#-----------------------------------------------------
rcp.perspective.name=Scoring tool

#-----------------------------------------------------
# Specific score tool import wizard
#-----------------------------------------------------
rcp.project.nature.extension.name=Scoring tool

#-----------------------------------------------------
# Editors
#-----------------------------------------------------
rcp.editor.name=Multipage editor
rcp.scoresheet.editor.name=Score sheet editor

#-----------------------------------------------------
# Commands
#-----------------------------------------------------
rcp.command.new_season=New Season
rcp.command.new_category=New category
rcp.command.new_club=New club
rcp.command.new_game=New game
rcp.command_export_as_pdf=Export as PDF
rcp.command.create_sample_project=Create sample project
rcp.command.quit=Quit
rcp.command.show_console=Show console
rcp.command.show_problem=Show problem
rcp.command.show_visitor_sheet=Show visitor sheet
rcp.command.show_hometeam_sheet=Show hometeam sheet
rcp.command.show_occupation_field=Show occupation field
rcp.command.show_general_display=Show general display
rcp.command.show_game_reports=Show game reports
rcp.command.import_actions=Import HTML File
rcp.command.search_game_by_team=Search game by team
rcp.command.search_game_by_date=Search game by date
rcp.command.show_lineup=Show line-up
rcp.command.show_outline=Show outline
rcp.command.set_score_nature=Set scoring tool nature
rcp.command.unset_score_nature=unset scoring tool nature
rcp.command.set_as_season_natureset as season nature

#-----------------------------------------------------
# miscellaneous
#-----------------------------------------------------
navigatorContent.name=Navigator
category.name=Scoring tool new wizard name
project.decorator.label=Project decorator
folder.decorator=Folder decorator

#-----------------------------------------------------
# Activities
#-----------------------------------------------------
disable.maven.activity=Disable maven activity
disable.pde.activity=Disable PDE activity
disable.ecore.activity=Disable ecore activity
disable.activity.java=Disable Java activity
disable.mwe.activity=Disable MWE activity
disable.debug.activity=Disable debug activity
disable.team.activity=Disable team activity
score.rcp.pde.activity=Disable RCP PDE activity
disable.annotation=Disable annotations activity
disable.externaltools.activity=Disable external tools activity
disable.importExport=Disable Import/Export activity
disable.XText.nature=Disable XText nature activity

#-----------------------------------------------------
#Popup menus
#-----------------------------------------------------
rcp.popup.new=New
rcp.popup2.copy=Copy
rcp.popup2.paste=Paste
rcp.popup2.remove=Remove
rcp.popup2.rename=Rename
rcp.popup2.refresh=Refresh
rcp.popup.set_as_season_folder=Set a season folder

