/**
 * European Scoring Tool For Baseball
 * Copyright (C) 2020  Patrick BRIAND
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * generated by Xtext 2.23.0
 */
package org.bpy.score.game.tests.language;

import com.google.inject.Inject;
import org.bpy.score.game.game.Action;
import org.bpy.score.game.game.BatterAction;
import org.bpy.score.game.game.BatterAdvanceOnBaseOnBall;
import org.bpy.score.game.game.BatterAdvanceOnCatcherInterference;
import org.bpy.score.game.game.BatterAdvanceOnDefensiveChoice;
import org.bpy.score.game.game.BatterAdvanceOnDoubleHit;
import org.bpy.score.game.game.BatterAdvanceOnFlyError;
import org.bpy.score.game.game.BatterAdvanceOnHitByPitch;
import org.bpy.score.game.game.BatterAdvanceOnHomeRun;
import org.bpy.score.game.game.BatterAdvanceOnInsidePark;
import org.bpy.score.game.game.BatterAdvanceOnIntentionalBaseOnBall;
import org.bpy.score.game.game.BatterAdvanceOnKPassBall;
import org.bpy.score.game.game.BatterAdvanceOnKWildPitch;
import org.bpy.score.game.game.BatterAdvanceOnKWithError;
import org.bpy.score.game.game.BatterAdvanceOnOccupedBall;
import org.bpy.score.game.game.BatterAdvanceOnReceiveError;
import org.bpy.score.game.game.BatterAdvanceOnSacrificeFlyWithError;
import org.bpy.score.game.game.BatterAdvanceOnSacrificeHitWithError;
import org.bpy.score.game.game.BatterAdvanceOnSingleHit;
import org.bpy.score.game.game.BatterAdvanceOnThrowError;
import org.bpy.score.game.game.BatterAdvanceOnTripleHit;
import org.bpy.score.game.game.Game;
import org.bpy.score.game.tests.GameInjectorProvider;
import org.bpy.score.game.util.ScoreGameAdvanceUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(GameInjectorProvider.class)
@SuppressWarnings("all")
public class BatterAdvanceChecker {
  @Inject
  @Extension
  private ParseHelper<Game> _parseHelper;

  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;

  @Test
  public void checkAdvanceOnSimple() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 1B7}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSingleHit)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSingleHit)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnDouble() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 2B8}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnDoubleHit)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnDoubleHit)element));
        Assertions.assertEquals(advanceValue, 2);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnTriple() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 3B9}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnTripleHit)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnTripleHit)element));
        Assertions.assertEquals(advanceValue, 3);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnSimpleBunt() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 1B7b}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSingleHit)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSingleHit)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnDoubleBunt() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 2B8b}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnDoubleHit)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnDoubleHit)element));
        Assertions.assertEquals(advanceValue, 2);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnTripleBunt() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 3B9b}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnTripleHit)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnTripleHit)element));
        Assertions.assertEquals(advanceValue, 3);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnHomerun() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> HR9}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnHomeRun)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnHomeRun)element));
        Assertions.assertEquals(advanceValue, 4);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnInsidePark() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> IHR9}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnInsidePark)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnInsidePark)element));
        Assertions.assertEquals(advanceValue, 4);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnBaseOnBall() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> BB}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnBaseOnBall)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnBaseOnBall)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnIntentionalBaseOnBall() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> IBB}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnIntentionalBaseOnBall)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnIntentionalBaseOnBall)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnHitByPitch() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> HP}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnHitByPitch)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnHitByPitch)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnCatcherInterference() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> CI}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnCatcherInterference)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnCatcherInterference)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnKPassBall() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KSPB}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnKPassBall)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnKPassBall)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnKWildPitch() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KSWP}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnKWildPitch)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnKWildPitch)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError01() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KS2E3}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnKWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnKWithError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError11() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KS2E3+}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnKWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnKWithError)element));
        Assertions.assertEquals(2, advanceValue);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError02() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KSE2T}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnKWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnKWithError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError12() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> KSE2T+}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnKWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnKWithError)element));
        Assertions.assertEquals(2, advanceValue);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError03() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 6E3}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnReceiveError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnReceiveError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError13() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> 6E3+}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnReceiveError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnReceiveError)element));
        Assertions.assertEquals(advanceValue, 2);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError04() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> E6T}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnThrowError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnThrowError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError14() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> E6T++}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnThrowError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnThrowError)element));
        Assertions.assertEquals(advanceValue, 3);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError05() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> E8F}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnFlyError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnFlyError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError15() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> E8F+}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnFlyError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnFlyError)element));
        Assertions.assertEquals(advanceValue, 2);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError06() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> SFE8}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSacrificeFlyWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSacrificeFlyWithError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError16() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> SFE8+++ }");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSacrificeFlyWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSacrificeFlyWithError)element));
        Assertions.assertEquals(4, advanceValue);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError07() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> SH5E3}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSacrificeHitWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSacrificeHitWithError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError17() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> SH5E3+}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSacrificeHitWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSacrificeHitWithError)element));
        Assertions.assertEquals(advanceValue, 2);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError08() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> SHE5T}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSacrificeHitWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSacrificeHitWithError)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkAdvanceOnError18() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> SHE5T++}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnSacrificeHitWithError)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnSacrificeHitWithError)element));
        Assertions.assertEquals(advanceValue, 3);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void advanceOnDefensiveChoice01() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> O5}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnOccupedBall)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnOccupedBall)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void advanceOnDefensiveChoice02() {
    try {
      final StringBuilder str = new StringBuilder(CommonResources.BASEBALL_STARTING_GAME);
      str.append("action { batter -> FC54}");
      str.append(CommonResources.ENDING_GAME);
      final Game parseResult = this._parseHelper.parse(str);
      this._validationTestHelper.assertNoErrors(parseResult);
      EObject _get = parseResult.getActions().getHalfInnings().get(0).getInningElements().get(0);
      final BatterAction element = ((Action) _get).getBatterAction();
      boolean checkResult = false;
      if ((element instanceof BatterAdvanceOnDefensiveChoice)) {
        final int advanceValue = ScoreGameAdvanceUtil.getBaseWin(((BatterAdvanceOnDefensiveChoice)element));
        Assertions.assertEquals(advanceValue, 1);
        checkResult = true;
      }
      Assertions.assertEquals(("" + Boolean.valueOf(checkResult)), "true");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
