/*
 * generated by Xtext 2.28.0
 */
package org.bpy.score.club.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.bpy.score.club.club.Club;
import org.bpy.score.club.club.ClubDescription;
import org.bpy.score.club.club.ClubPackage;
import org.bpy.score.club.club.Member;
import org.bpy.score.club.club.MemberStatus;
import org.bpy.score.club.club.Members;
import org.bpy.score.club.club.Officials;
import org.bpy.score.club.club.Player;
import org.bpy.score.club.club.ScoreKeeper;
import org.bpy.score.club.club.Team;
import org.bpy.score.club.club.Umpire;
import org.bpy.score.club.services.ClubGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ClubSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ClubGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ClubPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ClubPackage.CLUB:
				sequence_Club(context, (Club) semanticObject); 
				return; 
			case ClubPackage.CLUB_DESCRIPTION:
				sequence_ClubDescription(context, (ClubDescription) semanticObject); 
				return; 
			case ClubPackage.MEMBER:
				sequence_Member(context, (Member) semanticObject); 
				return; 
			case ClubPackage.MEMBER_STATUS:
				sequence_MemberStatus(context, (MemberStatus) semanticObject); 
				return; 
			case ClubPackage.MEMBERS:
				sequence_Members(context, (Members) semanticObject); 
				return; 
			case ClubPackage.OFFICIALS:
				sequence_Officials(context, (Officials) semanticObject); 
				return; 
			case ClubPackage.PLAYER:
				sequence_Player(context, (Player) semanticObject); 
				return; 
			case ClubPackage.SCORE_KEEPER:
				sequence_ScoreKeeper(context, (ScoreKeeper) semanticObject); 
				return; 
			case ClubPackage.TEAM:
				sequence_Team(context, (Team) semanticObject); 
				return; 
			case ClubPackage.UMPIRE:
				sequence_Umpire(context, (Umpire) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     ClubDescription returns ClubDescription
	 *
	 * Constraint:
	 *     (name=STRING members=Members teams+=Team* officials=Officials?)
	 * </pre>
	 */
	protected void sequence_ClubDescription(ISerializationContext context, ClubDescription semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Club returns Club
	 *
	 * Constraint:
	 *     (name=STRING clubDescription=ClubDescription)
	 * </pre>
	 */
	protected void sequence_Club(ISerializationContext context, Club semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClubPackage.Literals.CLUB__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClubPackage.Literals.CLUB__NAME));
			if (transientValues.isValueTransient(semanticObject, ClubPackage.Literals.CLUB__CLUB_DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClubPackage.Literals.CLUB__CLUB_DESCRIPTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getClubAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getClubAccess().getClubDescriptionClubDescriptionParserRuleCall_3_0(), semanticObject.getClubDescription());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MemberStatus returns MemberStatus
	 *
	 * Constraint:
	 *     (status+=STATUS status+=STATUS*)
	 * </pre>
	 */
	protected void sequence_MemberStatus(ISerializationContext context, MemberStatus semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Member returns Member
	 *
	 * Constraint:
	 *     (name=STRING shortName=STRING? licenceNumber=STRING shirtNumber=INT? status=MemberStatus?)
	 * </pre>
	 */
	protected void sequence_Member(ISerializationContext context, Member semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Members returns Members
	 *
	 * Constraint:
	 *     members+=Member+
	 * </pre>
	 */
	protected void sequence_Members(ISerializationContext context, Members semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Officials returns Officials
	 *
	 * Constraint:
	 *     officials+=Official*
	 * </pre>
	 */
	protected void sequence_Officials(ISerializationContext context, Officials semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Player returns Player
	 *
	 * Constraint:
	 *     playerName=[Member|STRING]
	 * </pre>
	 */
	protected void sequence_Player(ISerializationContext context, Player semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClubPackage.Literals.PLAYER__PLAYER_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClubPackage.Literals.PLAYER__PLAYER_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPlayerAccess().getPlayerNameMemberSTRINGTerminalRuleCall_3_0_1(), semanticObject.eGet(ClubPackage.Literals.PLAYER__PLAYER_NAME, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Official returns ScoreKeeper
	 *     ScoreKeeper returns ScoreKeeper
	 *
	 * Constraint:
	 *     name=[Member|STRING]
	 * </pre>
	 */
	protected void sequence_ScoreKeeper(ISerializationContext context, ScoreKeeper semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClubPackage.Literals.OFFICIAL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClubPackage.Literals.OFFICIAL__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScoreKeeperAccess().getNameMemberSTRINGTerminalRuleCall_3_0_1(), semanticObject.eGet(ClubPackage.Literals.OFFICIAL__NAME, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Team returns Team
	 *
	 * Constraint:
	 *     (name=STRING players+=Player*)
	 * </pre>
	 */
	protected void sequence_Team(ISerializationContext context, Team semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Official returns Umpire
	 *     Umpire returns Umpire
	 *
	 * Constraint:
	 *     name=[Member|STRING]
	 * </pre>
	 */
	protected void sequence_Umpire(ISerializationContext context, Umpire semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClubPackage.Literals.OFFICIAL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClubPackage.Literals.OFFICIAL__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUmpireAccess().getNameMemberSTRINGTerminalRuleCall_3_0_1(), semanticObject.eGet(ClubPackage.Literals.OFFICIAL__NAME, false));
		feeder.finish();
	}
	
	
}
