/*
 * European scorekeeper tool
 * Copyright (C) 2020  Patrick BRIAND
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * generated by Xtext 2.23.0
 *
 */
package org.bpy.score.club.tests

import com.google.inject.Inject
import org.bpy.score.club.club.Club
import org.bpy.score.club.club.ClubPackage
import org.bpy.score.club.validation.ClubValidator
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(ClubInjectorProvider)
class ValidationUnitTests {
	@Inject
	ParseHelper<Club> parseHelper
	
	@Inject ValidationTestHelper validator
	
	/* ======================================================================================== */
    /* Check general information about a club                                                   */	
	/* ======================================================================================== */
	
	/**
	 * A club must have at least one member
	 * check missing member
	 */
	@Test
	def void MinimalClubDescriptionWithoutMember() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
			}

		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertFalse(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		Assertions.assertEquals(errors.get(0).message,"mismatched input '}' expecting 'members'");
	}

	/**
	 * Minimal club description
	 * No error messages
	 */
	@Test
	def void MinimalClubDescriptionWithMember() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" licenceNumber = "00001";
				}
			}

		''')
		Assertions.assertNotNull(result)
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	/* ======================================================================================== */
    /* Check members description                                                                 */	
	/* ======================================================================================== */

	/**
	 * club description with two members
	 * No error messages
	 */
	@Test
	def void ClubDescriptionWithMembers() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" licenceNumber = "00001";
				    member name = "PEREZ Briana" licenceNumber = "00002";
				}
			}

		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	/**
	 * club description with member with short name
	 * No error messages
	 */
	@Test
	def void ClubDescriptionWithMembersWithShortName() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" shortName="lulu" licenceNumber = "00001";
				}
			}

		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	/**
	 * club description with member without license number.
	 */
	@Test
	def void ClubDescriptionWithMembersWithNoLicenseNumber() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" shortName="lulu";
				}
			}

		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertFalse(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		Assertions.assertEquals(errors.get(0).message,"mismatched input ';' expecting 'licenceNumber'");
	}
	
	/**
	 * club description with member duplicate license number
	 * Check the ClubValidator behavior
	 */
	@Test
	def void ClubDescriptionWithMembersWithDuplicateLicenseNumber() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" shortName="lulu" licenceNumber = "00001";
				    member name = "PEREZ Briana" licenceNumber = "00001";
				}
			}
		''')
		Assertions.assertNotNull(result)
		
		validator.assertError(result, ClubPackage.Literals.MEMBER,
			ClubValidator.DUPLICATE_LICENCE_NUMBER)	
	}
	
	/**
	 * club description with member who have a bad format license number
	 * Check the ClubValidator behavior
	 */
	@Test
	def void ClubDescriptionWithMembersWithNotANumberLicense() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" shortName="lulu" licenceNumber = "00001";
				    member name = "PEREZ Briana" licenceNumber = "A0001";
				}
			}
		''')
		Assertions.assertNotNull(result)
		
		validator.assertError(result, ClubPackage.Literals.MEMBER,
			ClubValidator.BAD_LICENCE_NUMBER)	
	}
	
	/**
	 * Check member with shortNumber
	 * Check good value for shirt number
	 */
	@Test
	def void ClubDescriptionWithMembersWithShortNumber() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" shortName="lulu" licenceNumber = "00001 shirtNumber=25";
				    member name = "PEREZ Briana" licenceNumber = "A0001"  shirtNumber=32;
				}
			}
		''')
		Assertions.assertNotNull(result)
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	/**
	 * Check member with shortNumber
	 * Check good value for shirt number
	 */
	@Test
	def void ClubDescriptionWithMembersWithBadShortNumber() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "NICKLES Bubba" shortName="lulu" licenceNumber = "00001" shirtNumber=250";
				}
			}
		''')
		Assertions.assertNotNull(result)
		
		validator.assertError(result, ClubPackage.Literals.MEMBER,
			ClubValidator.BAD_SHIRT_NUMBER)	
	}

	/**
	 * Check member with status (Only one status defined)
	 * No errors must be found
	 */
	@Test
	def void ClubDescriptionWithMembersStatus() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "Foreign" licenceNumber = "00001 shirtNumber=25" status=E;
				    member name = "European" licenceNumber = "00002"  shirtNumber=32 status=UE;
				    member name = "Tranfered" licenceNumber = "00003"  shirtNumber=32 status=M;
				    member name = "Extension" licenceNumber = "00004"  shirtNumber=32 status=Ex;
				    member name = "Young" licenceNumber = "00005"  shirtNumber=32 status=18U;
				}
			}
		''')
		Assertions.assertNotNull(result)
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	/**
	 * Check member with multiple status (Only one status defined)
	 * No errors must be found
	 */
	@Test
	def void ClubDescriptionWithMembersMultipleStatus() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "Foreign" licenceNumber = "00001 shirtNumber=25" status=E,UE,M,Ex,18U;
				}
			}
		''')
		Assertions.assertNotNull(result)
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	/* ======================================================================================== */
    /* Check category description                                                               */	
	/* ======================================================================================== */
	/**
	 * Check single category
	 */
	@Test
    def void checkSimpleCategory() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "Foreign" licenceNumber = "00001 shirtNumber=25" status=E,UE,M,Ex,18U;
				}
				
				team "D1" {
					player name = "Foreign";
				}	
			}
		''')
		Assertions.assertNotNull(result)
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	 }

	/**
	 * Check multiple categories
	 */
	 @Test
	 def void checkMultipleCategories() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "Foreign" licenceNumber = "00001 shirtNumber=25" status=E,UE,M,Ex,18U;
				}
				
				team "D1" {
					player name = "Foreign";
				}	
				
				team "D2" {
					player name = "Foreign";
				}	
			}
		''')
		Assertions.assertNotNull(result)
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		validator.assertNoError(result,	ClubValidator.DUPLICATE_CATEGORY)	
	 }

	/**
	 * Check duplicate categories
	 */
	@Test
	 def void checkDuplicateCategories() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "Foreign" licenceNumber = "00001 shirtNumber=25" status=E,UE,M,Ex,18U;
				}
				
				team "D1" {
					player name = "Foreign";
				}	
				
				team "D1" {
					player name = "Foreign";
				}	
			}
		''')
		Assertions.assertNotNull(result)
		
		validator.assertError(result, ClubPackage.Literals.TEAM,ClubValidator.DUPLICATE_CATEGORY)	
	 }
	 
	 /*
	  * Check empty team
	  */
	@Test
	 def void checkEmptyCategorie() {
		val result = parseHelper.parse('''
			club "UCLA" {
				city = "UCLA";
			
				members {
					member name = "Foreign" licenceNumber = "00001" shirtNumber=25 status=E,UE,M,Ex,18U;
				}
				
				team "D1" {
					player name = "Foreign";
				}	
			}
		''')
		Assertions.assertNotNull(result)
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	 }
}
