/**
 * generated by Xtext 2.28.0
 */
package org.bpy.score.game.game.util;

import org.bpy.score.game.game.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.bpy.score.game.game.GamePackage
 * @generated
 */
public class GameAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static GamePackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GameAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = GamePackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GameSwitch<Adapter> modelSwitch =
    new GameSwitch<Adapter>()
    {
      @Override
      public Adapter caseGame(Game object)
      {
        return createGameAdapter();
      }
      @Override
      public Adapter caseForfeitGame(ForfeitGame object)
      {
        return createForfeitGameAdapter();
      }
      @Override
      public Adapter caseActions(Actions object)
      {
        return createActionsAdapter();
      }
      @Override
      public Adapter caseGameResume(GameResume object)
      {
        return createGameResumeAdapter();
      }
      @Override
      public Adapter caseHalfInning(HalfInning object)
      {
        return createHalfInningAdapter();
      }
      @Override
      public Adapter caseCommands(Commands object)
      {
        return createCommandsAdapter();
      }
      @Override
      public Adapter caseMoveCommand(MoveCommand object)
      {
        return createMoveCommandAdapter();
      }
      @Override
      public Adapter caseSelectedBatterCommand(SelectedBatterCommand object)
      {
        return createSelectedBatterCommandAdapter();
      }
      @Override
      public Adapter caseNote(Note object)
      {
        return createNoteAdapter();
      }
      @Override
      public Adapter caseInningSetting(InningSetting object)
      {
        return createInningSettingAdapter();
      }
      @Override
      public Adapter caseAction(Action object)
      {
        return createActionAdapter();
      }
      @Override
      public Adapter casePitches(Pitches object)
      {
        return createPitchesAdapter();
      }
      @Override
      public Adapter casePitch(Pitch object)
      {
        return createPitchAdapter();
      }
      @Override
      public Adapter caseRunnerAction(RunnerAction object)
      {
        return createRunnerActionAdapter();
      }
      @Override
      public Adapter caseOtherRunnerAction(OtherRunnerAction object)
      {
        return createOtherRunnerActionAdapter();
      }
      @Override
      public Adapter caseRunnerOut(RunnerOut object)
      {
        return createRunnerOutAdapter();
      }
      @Override
      public Adapter caseRunnerAdvance(RunnerAdvance object)
      {
        return createRunnerAdvanceAdapter();
      }
      @Override
      public Adapter caseSubstitutionEvent(SubstitutionEvent object)
      {
        return createSubstitutionEventAdapter();
      }
      @Override
      public Adapter caseSubstitutionDescription(SubstitutionDescription object)
      {
        return createSubstitutionDescriptionAdapter();
      }
      @Override
      public Adapter caseNewDefensivePosition(NewDefensivePosition object)
      {
        return createNewDefensivePositionAdapter();
      }
      @Override
      public Adapter caseReplacement(Replacement object)
      {
        return createReplacementAdapter();
      }
      @Override
      public Adapter caseBatterAction(BatterAction object)
      {
        return createBatterActionAdapter();
      }
      @Override
      public Adapter caseBatterBalk(BatterBalk object)
      {
        return createBatterBalkAdapter();
      }
      @Override
      public Adapter caseBatterMustOutOnFlyFoulBall(BatterMustOutOnFlyFoulBall object)
      {
        return createBatterMustOutOnFlyFoulBallAdapter();
      }
      @Override
      public Adapter caseBatterLostTurn(BatterLostTurn object)
      {
        return createBatterLostTurnAdapter();
      }
      @Override
      public Adapter caseBatterAdvance(BatterAdvance object)
      {
        return createBatterAdvanceAdapter();
      }
      @Override
      public Adapter caseDefensiveChoiceForBatter(DefensiveChoiceForBatter object)
      {
        return createDefensiveChoiceForBatterAdapter();
      }
      @Override
      public Adapter caseMoreAdanceFail(MoreAdanceFail object)
      {
        return createMoreAdanceFailAdapter();
      }
      @Override
      public Adapter caseAdvanceWithContinuation(AdvanceWithContinuation object)
      {
        return createAdvanceWithContinuationAdapter();
      }
      @Override
      public Adapter caseOtherBatterAdvance(OtherBatterAdvance object)
      {
        return createOtherBatterAdvanceAdapter();
      }
      @Override
      public Adapter caseHit(Hit object)
      {
        return createHitAdapter();
      }
      @Override
      public Adapter caseDecisiveError(DecisiveError object)
      {
        return createDecisiveErrorAdapter();
      }
      @Override
      public Adapter caseBatterOut(BatterOut object)
      {
        return createBatterOutAdapter();
      }
      @Override
      public Adapter caseFielderOut(FielderOut object)
      {
        return createFielderOutAdapter();
      }
      @Override
      public Adapter caseStrikeOut(StrikeOut object)
      {
        return createStrikeOutAdapter();
      }
      @Override
      public Adapter caseCurrentBatter(CurrentBatter object)
      {
        return createCurrentBatterAdapter();
      }
      @Override
      public Adapter caseCurrentRunner(CurrentRunner object)
      {
        return createCurrentRunnerAdapter();
      }
      @Override
      public Adapter caseLineUp(LineUp object)
      {
        return createLineUpAdapter();
      }
      @Override
      public Adapter caseLineUpEntry(LineUpEntry object)
      {
        return createLineUpEntryAdapter();
      }
      @Override
      public Adapter caseRoster(Roster object)
      {
        return createRosterAdapter();
      }
      @Override
      public Adapter casePlayer(Player object)
      {
        return createPlayerAdapter();
      }
      @Override
      public Adapter caseDescription(Description object)
      {
        return createDescriptionAdapter();
      }
      @Override
      public Adapter caseNotes(Notes object)
      {
        return createNotesAdapter();
      }
      @Override
      public Adapter caseScoreKeepers(ScoreKeepers object)
      {
        return createScoreKeepersAdapter();
      }
      @Override
      public Adapter caseUmpires(Umpires object)
      {
        return createUmpiresAdapter();
      }
      @Override
      public Adapter caseRunnerMustBeOutOnError(RunnerMustBeOutOnError object)
      {
        return createRunnerMustBeOutOnErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnError(RunnerDontAdvanceOnError object)
      {
        return createRunnerDontAdvanceOnErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnPickOffWithError(RunnerDontAdvanceOnPickOffWithError object)
      {
        return createRunnerDontAdvanceOnPickOffWithErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnCaughtStealingWithError(RunnerDontAdvanceOnCaughtStealingWithError object)
      {
        return createRunnerDontAdvanceOnCaughtStealingWithErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnThrowError(RunnerDontAdvanceOnThrowError object)
      {
        return createRunnerDontAdvanceOnThrowErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnReceiveError(RunnerDontAdvanceOnReceiveError object)
      {
        return createRunnerDontAdvanceOnReceiveErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnNonDecisiveThrowError(RunnerDontAdvanceOnNonDecisiveThrowError object)
      {
        return createRunnerDontAdvanceOnNonDecisiveThrowErrorAdapter();
      }
      @Override
      public Adapter caseRunnerDontAdvanceOnNonDecisiveReceiveError(RunnerDontAdvanceOnNonDecisiveReceiveError object)
      {
        return createRunnerDontAdvanceOnNonDecisiveReceiveErrorAdapter();
      }
      @Override
      public Adapter caseRunnerOutOnCaugthStealing(RunnerOutOnCaugthStealing object)
      {
        return createRunnerOutOnCaugthStealingAdapter();
      }
      @Override
      public Adapter caseRunnerOutOnPickOff(RunnerOutOnPickOff object)
      {
        return createRunnerOutOnPickOffAdapter();
      }
      @Override
      public Adapter caseRunnerOutOnFielderAction(RunnerOutOnFielderAction object)
      {
        return createRunnerOutOnFielderActionAdapter();
      }
      @Override
      public Adapter caseRunnerOutByRules(RunnerOutByRules object)
      {
        return createRunnerOutByRulesAdapter();
      }
      @Override
      public Adapter caseRunnerOutOnAppeal(RunnerOutOnAppeal object)
      {
        return createRunnerOutOnAppealAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceByBatterAction(RunnerAdvanceByBatterAction object)
      {
        return createRunnerAdvanceByBatterActionAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnError(RunnerAdvanceOnError object)
      {
        return createRunnerAdvanceOnErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnStolenBase(RunnerAdvanceOnStolenBase object)
      {
        return createRunnerAdvanceOnStolenBaseAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnWildPitch(RunnerAdvanceOnWildPitch object)
      {
        return createRunnerAdvanceOnWildPitchAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnPassBall(RunnerAdvanceOnPassBall object)
      {
        return createRunnerAdvanceOnPassBallAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnBalk(RunnerAdvanceOnBalk object)
      {
        return createRunnerAdvanceOnBalkAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnPickOffWithError(RunnerAdvanceOnPickOffWithError object)
      {
        return createRunnerAdvanceOnPickOffWithErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnCaughtStealingWithError(RunnerAdvanceOnCaughtStealingWithError object)
      {
        return createRunnerAdvanceOnCaughtStealingWithErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnOccupedBall(RunnerAdvanceOnOccupedBall object)
      {
        return createRunnerAdvanceOnOccupedBallAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnNoDecisiveObstruction(RunnerAdvanceOnNoDecisiveObstruction object)
      {
        return createRunnerAdvanceOnNoDecisiveObstructionAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnDecisiveObstruction(RunnerAdvanceOnDecisiveObstruction object)
      {
        return createRunnerAdvanceOnDecisiveObstructionAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnThrow(RunnerAdvanceOnThrow object)
      {
        return createRunnerAdvanceOnThrowAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnIndiference(RunnerAdvanceOnIndiference object)
      {
        return createRunnerAdvanceOnIndiferenceAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnThrowError(RunnerAdvanceOnThrowError object)
      {
        return createRunnerAdvanceOnThrowErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnReceiveError(RunnerAdvanceOnReceiveError object)
      {
        return createRunnerAdvanceOnReceiveErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnNonDecisiveThrowError(RunnerAdvanceOnNonDecisiveThrowError object)
      {
        return createRunnerAdvanceOnNonDecisiveThrowErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnNonDecisiveReceiveError(RunnerAdvanceOnNonDecisiveReceiveError object)
      {
        return createRunnerAdvanceOnNonDecisiveReceiveErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnRule(RunnerAdvanceOnRule object)
      {
        return createRunnerAdvanceOnRuleAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnOtherPlayerError(RunnerAdvanceOnOtherPlayerError object)
      {
        return createRunnerAdvanceOnOtherPlayerErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnFielderChoice(RunnerAdvanceOnFielderChoice object)
      {
        return createRunnerAdvanceOnFielderChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnOccupedBall(BatterAdvanceOnOccupedBall object)
      {
        return createBatterAdvanceOnOccupedBallAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnDefensiveChoice(BatterAdvanceOnDefensiveChoice object)
      {
        return createBatterAdvanceOnDefensiveChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnIndiference(BatterAdvanceOnIndiference object)
      {
        return createBatterAdvanceOnIndiferenceAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnNonDecisiveFlyError(RunnerAdvanceOnNonDecisiveFlyError object)
      {
        return createRunnerAdvanceOnNonDecisiveFlyErrorAdapter();
      }
      @Override
      public Adapter caseRunnerAdvanceOnDefensiveChoice(RunnerAdvanceOnDefensiveChoice object)
      {
        return createRunnerAdvanceOnDefensiveChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnBaseOnBall(BatterAdvanceOnBaseOnBall object)
      {
        return createBatterAdvanceOnBaseOnBallAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnIntentionalBaseOnBall(BatterAdvanceOnIntentionalBaseOnBall object)
      {
        return createBatterAdvanceOnIntentionalBaseOnBallAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnHitByPitch(BatterAdvanceOnHitByPitch object)
      {
        return createBatterAdvanceOnHitByPitchAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnKPassBall(BatterAdvanceOnKPassBall object)
      {
        return createBatterAdvanceOnKPassBallAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnKWildPitch(BatterAdvanceOnKWildPitch object)
      {
        return createBatterAdvanceOnKWildPitchAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnKAbr(BatterAdvanceOnKAbr object)
      {
        return createBatterAdvanceOnKAbrAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnKWithError(BatterAdvanceOnKWithError object)
      {
        return createBatterAdvanceOnKWithErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnSacrificeHitWithError(BatterAdvanceOnSacrificeHitWithError object)
      {
        return createBatterAdvanceOnSacrificeHitWithErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnSacrificeHitWithFielderChoice(BatterAdvanceOnSacrificeHitWithFielderChoice object)
      {
        return createBatterAdvanceOnSacrificeHitWithFielderChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnSacrificeFlyWithError(BatterAdvanceOnSacrificeFlyWithError object)
      {
        return createBatterAdvanceOnSacrificeFlyWithErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnSacrificeFlyWithFielderChoice(BatterAdvanceOnSacrificeFlyWithFielderChoice object)
      {
        return createBatterAdvanceOnSacrificeFlyWithFielderChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnCatcherInterference(BatterAdvanceOnCatcherInterference object)
      {
        return createBatterAdvanceOnCatcherInterferenceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnObstruction(BatterAdvanceOnObstruction object)
      {
        return createBatterAdvanceOnObstructionAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnKWithFielderChoice(BatterAdvanceOnKWithFielderChoice object)
      {
        return createBatterAdvanceOnKWithFielderChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnGdpWithFielderChoice(BatterAdvanceOnGdpWithFielderChoice object)
      {
        return createBatterAdvanceOnGdpWithFielderChoiceAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnSingleHit(BatterAdvanceOnSingleHit object)
      {
        return createBatterAdvanceOnSingleHitAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnDoubleHit(BatterAdvanceOnDoubleHit object)
      {
        return createBatterAdvanceOnDoubleHitAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnTripleHit(BatterAdvanceOnTripleHit object)
      {
        return createBatterAdvanceOnTripleHitAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnHomeRun(BatterAdvanceOnHomeRun object)
      {
        return createBatterAdvanceOnHomeRunAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnInsidePark(BatterAdvanceOnInsidePark object)
      {
        return createBatterAdvanceOnInsideParkAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnFlyError(BatterAdvanceOnFlyError object)
      {
        return createBatterAdvanceOnFlyErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnPopError(BatterAdvanceOnPopError object)
      {
        return createBatterAdvanceOnPopErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnReceiveError(BatterAdvanceOnReceiveError object)
      {
        return createBatterAdvanceOnReceiveErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnThrowError(BatterAdvanceOnThrowError object)
      {
        return createBatterAdvanceOnThrowErrorAdapter();
      }
      @Override
      public Adapter caseBatterAdvanceOnGdpWithError(BatterAdvanceOnGdpWithError object)
      {
        return createBatterAdvanceOnGdpWithErrorAdapter();
      }
      @Override
      public Adapter caseBatterOutOnFlyed(BatterOutOnFlyed object)
      {
        return createBatterOutOnFlyedAdapter();
      }
      @Override
      public Adapter caseBatterOutOnLine(BatterOutOnLine object)
      {
        return createBatterOutOnLineAdapter();
      }
      @Override
      public Adapter caseBatterOutOnPopped(BatterOutOnPopped object)
      {
        return createBatterOutOnPoppedAdapter();
      }
      @Override
      public Adapter caseBatterOutOnFlyedFallBall(BatterOutOnFlyedFallBall object)
      {
        return createBatterOutOnFlyedFallBallAdapter();
      }
      @Override
      public Adapter caseBatterOutOnPoppedFallBall(BatterOutOnPoppedFallBall object)
      {
        return createBatterOutOnPoppedFallBallAdapter();
      }
      @Override
      public Adapter caseBatterOutOnLineDriveFallBall(BatterOutOnLineDriveFallBall object)
      {
        return createBatterOutOnLineDriveFallBallAdapter();
      }
      @Override
      public Adapter caseBatterOutOnGroundedBall(BatterOutOnGroundedBall object)
      {
        return createBatterOutOnGroundedBallAdapter();
      }
      @Override
      public Adapter caseBatterOutByRule(BatterOutByRule object)
      {
        return createBatterOutByRuleAdapter();
      }
      @Override
      public Adapter caseBatterOutOnAppeal(BatterOutOnAppeal object)
      {
        return createBatterOutOnAppealAdapter();
      }
      @Override
      public Adapter caseBatterOutOnGroundedDoublePlay(BatterOutOnGroundedDoublePlay object)
      {
        return createBatterOutOnGroundedDoublePlayAdapter();
      }
      @Override
      public Adapter caseBatterOutOnSacrificeFly(BatterOutOnSacrificeFly object)
      {
        return createBatterOutOnSacrificeFlyAdapter();
      }
      @Override
      public Adapter caseBatterOutOnSacrificeFlyFallBall(BatterOutOnSacrificeFlyFallBall object)
      {
        return createBatterOutOnSacrificeFlyFallBallAdapter();
      }
      @Override
      public Adapter caseBatterOutOnSacrificeHit(BatterOutOnSacrificeHit object)
      {
        return createBatterOutOnSacrificeHitAdapter();
      }
      @Override
      public Adapter caseBatterOutOnInfieldFly(BatterOutOnInfieldFly object)
      {
        return createBatterOutOnInfieldFlyAdapter();
      }
      @Override
      public Adapter caseBatterOutOnSwingedStrike(BatterOutOnSwingedStrike object)
      {
        return createBatterOutOnSwingedStrikeAdapter();
      }
      @Override
      public Adapter caseBatterOutOnLookedStrike(BatterOutOnLookedStrike object)
      {
        return createBatterOutOnLookedStrikeAdapter();
      }
      @Override
      public Adapter caseBatterOutOnReleasedStrike(BatterOutOnReleasedStrike object)
      {
        return createBatterOutOnReleasedStrikeAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Game
   * @generated
   */
  public Adapter createGameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.ForfeitGame <em>Forfeit Game</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.ForfeitGame
   * @generated
   */
  public Adapter createForfeitGameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Actions
   * @generated
   */
  public Adapter createActionsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.GameResume <em>Resume</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.GameResume
   * @generated
   */
  public Adapter createGameResumeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.HalfInning <em>Half Inning</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.HalfInning
   * @generated
   */
  public Adapter createHalfInningAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Commands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Commands
   * @generated
   */
  public Adapter createCommandsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.MoveCommand <em>Move Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.MoveCommand
   * @generated
   */
  public Adapter createMoveCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.SelectedBatterCommand <em>Selected Batter Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.SelectedBatterCommand
   * @generated
   */
  public Adapter createSelectedBatterCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Note <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Note
   * @generated
   */
  public Adapter createNoteAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.InningSetting <em>Inning Setting</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.InningSetting
   * @generated
   */
  public Adapter createInningSettingAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Action
   * @generated
   */
  public Adapter createActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Pitches <em>Pitches</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Pitches
   * @generated
   */
  public Adapter createPitchesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Pitch <em>Pitch</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Pitch
   * @generated
   */
  public Adapter createPitchAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAction <em>Runner Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAction
   * @generated
   */
  public Adapter createRunnerActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.OtherRunnerAction <em>Other Runner Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.OtherRunnerAction
   * @generated
   */
  public Adapter createOtherRunnerActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerOut <em>Runner Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerOut
   * @generated
   */
  public Adapter createRunnerOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvance <em>Runner Advance</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvance
   * @generated
   */
  public Adapter createRunnerAdvanceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.SubstitutionEvent <em>Substitution Event</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.SubstitutionEvent
   * @generated
   */
  public Adapter createSubstitutionEventAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.SubstitutionDescription <em>Substitution Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.SubstitutionDescription
   * @generated
   */
  public Adapter createSubstitutionDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.NewDefensivePosition <em>New Defensive Position</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.NewDefensivePosition
   * @generated
   */
  public Adapter createNewDefensivePositionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Replacement <em>Replacement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Replacement
   * @generated
   */
  public Adapter createReplacementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAction <em>Batter Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAction
   * @generated
   */
  public Adapter createBatterActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterBalk <em>Batter Balk</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterBalk
   * @generated
   */
  public Adapter createBatterBalkAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterMustOutOnFlyFoulBall <em>Batter Must Out On Fly Foul Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterMustOutOnFlyFoulBall
   * @generated
   */
  public Adapter createBatterMustOutOnFlyFoulBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterLostTurn <em>Batter Lost Turn</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterLostTurn
   * @generated
   */
  public Adapter createBatterLostTurnAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvance <em>Batter Advance</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvance
   * @generated
   */
  public Adapter createBatterAdvanceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.DefensiveChoiceForBatter <em>Defensive Choice For Batter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.DefensiveChoiceForBatter
   * @generated
   */
  public Adapter createDefensiveChoiceForBatterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.MoreAdanceFail <em>More Adance Fail</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.MoreAdanceFail
   * @generated
   */
  public Adapter createMoreAdanceFailAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.AdvanceWithContinuation <em>Advance With Continuation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.AdvanceWithContinuation
   * @generated
   */
  public Adapter createAdvanceWithContinuationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.OtherBatterAdvance <em>Other Batter Advance</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.OtherBatterAdvance
   * @generated
   */
  public Adapter createOtherBatterAdvanceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Hit <em>Hit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Hit
   * @generated
   */
  public Adapter createHitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.DecisiveError <em>Decisive Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.DecisiveError
   * @generated
   */
  public Adapter createDecisiveErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOut <em>Batter Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOut
   * @generated
   */
  public Adapter createBatterOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.FielderOut <em>Fielder Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.FielderOut
   * @generated
   */
  public Adapter createFielderOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.StrikeOut <em>Strike Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.StrikeOut
   * @generated
   */
  public Adapter createStrikeOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.CurrentBatter <em>Current Batter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.CurrentBatter
   * @generated
   */
  public Adapter createCurrentBatterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.CurrentRunner <em>Current Runner</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.CurrentRunner
   * @generated
   */
  public Adapter createCurrentRunnerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.LineUp <em>Line Up</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.LineUp
   * @generated
   */
  public Adapter createLineUpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.LineUpEntry <em>Line Up Entry</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.LineUpEntry
   * @generated
   */
  public Adapter createLineUpEntryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Roster <em>Roster</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Roster
   * @generated
   */
  public Adapter createRosterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Player <em>Player</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Player
   * @generated
   */
  public Adapter createPlayerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Description
   * @generated
   */
  public Adapter createDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Notes <em>Notes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Notes
   * @generated
   */
  public Adapter createNotesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.ScoreKeepers <em>Score Keepers</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.ScoreKeepers
   * @generated
   */
  public Adapter createScoreKeepersAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.Umpires <em>Umpires</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.Umpires
   * @generated
   */
  public Adapter createUmpiresAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerMustBeOutOnError <em>Runner Must Be Out On Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerMustBeOutOnError
   * @generated
   */
  public Adapter createRunnerMustBeOutOnErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnError <em>Runner Dont Advance On Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnPickOffWithError <em>Runner Dont Advance On Pick Off With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnPickOffWithError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnPickOffWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnCaughtStealingWithError <em>Runner Dont Advance On Caught Stealing With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnCaughtStealingWithError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnCaughtStealingWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnThrowError <em>Runner Dont Advance On Throw Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnThrowError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnThrowErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnReceiveError <em>Runner Dont Advance On Receive Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnReceiveError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnReceiveErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnNonDecisiveThrowError <em>Runner Dont Advance On Non Decisive Throw Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnNonDecisiveThrowError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnNonDecisiveThrowErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerDontAdvanceOnNonDecisiveReceiveError <em>Runner Dont Advance On Non Decisive Receive Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerDontAdvanceOnNonDecisiveReceiveError
   * @generated
   */
  public Adapter createRunnerDontAdvanceOnNonDecisiveReceiveErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerOutOnCaugthStealing <em>Runner Out On Caugth Stealing</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerOutOnCaugthStealing
   * @generated
   */
  public Adapter createRunnerOutOnCaugthStealingAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerOutOnPickOff <em>Runner Out On Pick Off</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerOutOnPickOff
   * @generated
   */
  public Adapter createRunnerOutOnPickOffAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerOutOnFielderAction <em>Runner Out On Fielder Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerOutOnFielderAction
   * @generated
   */
  public Adapter createRunnerOutOnFielderActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerOutByRules <em>Runner Out By Rules</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerOutByRules
   * @generated
   */
  public Adapter createRunnerOutByRulesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerOutOnAppeal <em>Runner Out On Appeal</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerOutOnAppeal
   * @generated
   */
  public Adapter createRunnerOutOnAppealAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceByBatterAction <em>Runner Advance By Batter Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceByBatterAction
   * @generated
   */
  public Adapter createRunnerAdvanceByBatterActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnError <em>Runner Advance On Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnError
   * @generated
   */
  public Adapter createRunnerAdvanceOnErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnStolenBase <em>Runner Advance On Stolen Base</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnStolenBase
   * @generated
   */
  public Adapter createRunnerAdvanceOnStolenBaseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnWildPitch <em>Runner Advance On Wild Pitch</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnWildPitch
   * @generated
   */
  public Adapter createRunnerAdvanceOnWildPitchAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnPassBall <em>Runner Advance On Pass Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnPassBall
   * @generated
   */
  public Adapter createRunnerAdvanceOnPassBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnBalk <em>Runner Advance On Balk</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnBalk
   * @generated
   */
  public Adapter createRunnerAdvanceOnBalkAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnPickOffWithError <em>Runner Advance On Pick Off With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnPickOffWithError
   * @generated
   */
  public Adapter createRunnerAdvanceOnPickOffWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnCaughtStealingWithError <em>Runner Advance On Caught Stealing With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnCaughtStealingWithError
   * @generated
   */
  public Adapter createRunnerAdvanceOnCaughtStealingWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnOccupedBall <em>Runner Advance On Occuped Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnOccupedBall
   * @generated
   */
  public Adapter createRunnerAdvanceOnOccupedBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnNoDecisiveObstruction <em>Runner Advance On No Decisive Obstruction</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnNoDecisiveObstruction
   * @generated
   */
  public Adapter createRunnerAdvanceOnNoDecisiveObstructionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnDecisiveObstruction <em>Runner Advance On Decisive Obstruction</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnDecisiveObstruction
   * @generated
   */
  public Adapter createRunnerAdvanceOnDecisiveObstructionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnThrow <em>Runner Advance On Throw</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnThrow
   * @generated
   */
  public Adapter createRunnerAdvanceOnThrowAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnIndiference <em>Runner Advance On Indiference</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnIndiference
   * @generated
   */
  public Adapter createRunnerAdvanceOnIndiferenceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnThrowError <em>Runner Advance On Throw Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnThrowError
   * @generated
   */
  public Adapter createRunnerAdvanceOnThrowErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnReceiveError <em>Runner Advance On Receive Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnReceiveError
   * @generated
   */
  public Adapter createRunnerAdvanceOnReceiveErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveThrowError <em>Runner Advance On Non Decisive Throw Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveThrowError
   * @generated
   */
  public Adapter createRunnerAdvanceOnNonDecisiveThrowErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveReceiveError <em>Runner Advance On Non Decisive Receive Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveReceiveError
   * @generated
   */
  public Adapter createRunnerAdvanceOnNonDecisiveReceiveErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnRule <em>Runner Advance On Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnRule
   * @generated
   */
  public Adapter createRunnerAdvanceOnRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnOtherPlayerError <em>Runner Advance On Other Player Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnOtherPlayerError
   * @generated
   */
  public Adapter createRunnerAdvanceOnOtherPlayerErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnFielderChoice <em>Runner Advance On Fielder Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnFielderChoice
   * @generated
   */
  public Adapter createRunnerAdvanceOnFielderChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnOccupedBall <em>Batter Advance On Occuped Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnOccupedBall
   * @generated
   */
  public Adapter createBatterAdvanceOnOccupedBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnDefensiveChoice <em>Batter Advance On Defensive Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnDefensiveChoice
   * @generated
   */
  public Adapter createBatterAdvanceOnDefensiveChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnIndiference <em>Batter Advance On Indiference</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnIndiference
   * @generated
   */
  public Adapter createBatterAdvanceOnIndiferenceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveFlyError <em>Runner Advance On Non Decisive Fly Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnNonDecisiveFlyError
   * @generated
   */
  public Adapter createRunnerAdvanceOnNonDecisiveFlyErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.RunnerAdvanceOnDefensiveChoice <em>Runner Advance On Defensive Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.RunnerAdvanceOnDefensiveChoice
   * @generated
   */
  public Adapter createRunnerAdvanceOnDefensiveChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnBaseOnBall <em>Batter Advance On Base On Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnBaseOnBall
   * @generated
   */
  public Adapter createBatterAdvanceOnBaseOnBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnIntentionalBaseOnBall <em>Batter Advance On Intentional Base On Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnIntentionalBaseOnBall
   * @generated
   */
  public Adapter createBatterAdvanceOnIntentionalBaseOnBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnHitByPitch <em>Batter Advance On Hit By Pitch</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnHitByPitch
   * @generated
   */
  public Adapter createBatterAdvanceOnHitByPitchAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnKPassBall <em>Batter Advance On KPass Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnKPassBall
   * @generated
   */
  public Adapter createBatterAdvanceOnKPassBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnKWildPitch <em>Batter Advance On KWild Pitch</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnKWildPitch
   * @generated
   */
  public Adapter createBatterAdvanceOnKWildPitchAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnKAbr <em>Batter Advance On KAbr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnKAbr
   * @generated
   */
  public Adapter createBatterAdvanceOnKAbrAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnKWithError <em>Batter Advance On KWith Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnKWithError
   * @generated
   */
  public Adapter createBatterAdvanceOnKWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnSacrificeHitWithError <em>Batter Advance On Sacrifice Hit With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnSacrificeHitWithError
   * @generated
   */
  public Adapter createBatterAdvanceOnSacrificeHitWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnSacrificeHitWithFielderChoice <em>Batter Advance On Sacrifice Hit With Fielder Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnSacrificeHitWithFielderChoice
   * @generated
   */
  public Adapter createBatterAdvanceOnSacrificeHitWithFielderChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnSacrificeFlyWithError <em>Batter Advance On Sacrifice Fly With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnSacrificeFlyWithError
   * @generated
   */
  public Adapter createBatterAdvanceOnSacrificeFlyWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnSacrificeFlyWithFielderChoice <em>Batter Advance On Sacrifice Fly With Fielder Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnSacrificeFlyWithFielderChoice
   * @generated
   */
  public Adapter createBatterAdvanceOnSacrificeFlyWithFielderChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnCatcherInterference <em>Batter Advance On Catcher Interference</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnCatcherInterference
   * @generated
   */
  public Adapter createBatterAdvanceOnCatcherInterferenceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnObstruction <em>Batter Advance On Obstruction</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnObstruction
   * @generated
   */
  public Adapter createBatterAdvanceOnObstructionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnKWithFielderChoice <em>Batter Advance On KWith Fielder Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnKWithFielderChoice
   * @generated
   */
  public Adapter createBatterAdvanceOnKWithFielderChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnGdpWithFielderChoice <em>Batter Advance On Gdp With Fielder Choice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnGdpWithFielderChoice
   * @generated
   */
  public Adapter createBatterAdvanceOnGdpWithFielderChoiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnSingleHit <em>Batter Advance On Single Hit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnSingleHit
   * @generated
   */
  public Adapter createBatterAdvanceOnSingleHitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnDoubleHit <em>Batter Advance On Double Hit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnDoubleHit
   * @generated
   */
  public Adapter createBatterAdvanceOnDoubleHitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnTripleHit <em>Batter Advance On Triple Hit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnTripleHit
   * @generated
   */
  public Adapter createBatterAdvanceOnTripleHitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnHomeRun <em>Batter Advance On Home Run</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnHomeRun
   * @generated
   */
  public Adapter createBatterAdvanceOnHomeRunAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnInsidePark <em>Batter Advance On Inside Park</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnInsidePark
   * @generated
   */
  public Adapter createBatterAdvanceOnInsideParkAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnFlyError <em>Batter Advance On Fly Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnFlyError
   * @generated
   */
  public Adapter createBatterAdvanceOnFlyErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnPopError <em>Batter Advance On Pop Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnPopError
   * @generated
   */
  public Adapter createBatterAdvanceOnPopErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnReceiveError <em>Batter Advance On Receive Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnReceiveError
   * @generated
   */
  public Adapter createBatterAdvanceOnReceiveErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnThrowError <em>Batter Advance On Throw Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnThrowError
   * @generated
   */
  public Adapter createBatterAdvanceOnThrowErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterAdvanceOnGdpWithError <em>Batter Advance On Gdp With Error</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterAdvanceOnGdpWithError
   * @generated
   */
  public Adapter createBatterAdvanceOnGdpWithErrorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnFlyed <em>Batter Out On Flyed</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnFlyed
   * @generated
   */
  public Adapter createBatterOutOnFlyedAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnLine <em>Batter Out On Line</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnLine
   * @generated
   */
  public Adapter createBatterOutOnLineAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnPopped <em>Batter Out On Popped</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnPopped
   * @generated
   */
  public Adapter createBatterOutOnPoppedAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnFlyedFallBall <em>Batter Out On Flyed Fall Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnFlyedFallBall
   * @generated
   */
  public Adapter createBatterOutOnFlyedFallBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnPoppedFallBall <em>Batter Out On Popped Fall Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnPoppedFallBall
   * @generated
   */
  public Adapter createBatterOutOnPoppedFallBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnLineDriveFallBall <em>Batter Out On Line Drive Fall Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnLineDriveFallBall
   * @generated
   */
  public Adapter createBatterOutOnLineDriveFallBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnGroundedBall <em>Batter Out On Grounded Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnGroundedBall
   * @generated
   */
  public Adapter createBatterOutOnGroundedBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutByRule <em>Batter Out By Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutByRule
   * @generated
   */
  public Adapter createBatterOutByRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnAppeal <em>Batter Out On Appeal</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnAppeal
   * @generated
   */
  public Adapter createBatterOutOnAppealAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnGroundedDoublePlay <em>Batter Out On Grounded Double Play</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnGroundedDoublePlay
   * @generated
   */
  public Adapter createBatterOutOnGroundedDoublePlayAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnSacrificeFly <em>Batter Out On Sacrifice Fly</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnSacrificeFly
   * @generated
   */
  public Adapter createBatterOutOnSacrificeFlyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnSacrificeFlyFallBall <em>Batter Out On Sacrifice Fly Fall Ball</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnSacrificeFlyFallBall
   * @generated
   */
  public Adapter createBatterOutOnSacrificeFlyFallBallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnSacrificeHit <em>Batter Out On Sacrifice Hit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnSacrificeHit
   * @generated
   */
  public Adapter createBatterOutOnSacrificeHitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnInfieldFly <em>Batter Out On Infield Fly</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnInfieldFly
   * @generated
   */
  public Adapter createBatterOutOnInfieldFlyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnSwingedStrike <em>Batter Out On Swinged Strike</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnSwingedStrike
   * @generated
   */
  public Adapter createBatterOutOnSwingedStrikeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnLookedStrike <em>Batter Out On Looked Strike</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnLookedStrike
   * @generated
   */
  public Adapter createBatterOutOnLookedStrikeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.bpy.score.game.game.BatterOutOnReleasedStrike <em>Batter Out On Released Strike</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.bpy.score.game.game.BatterOutOnReleasedStrike
   * @generated
   */
  public Adapter createBatterOutOnReleasedStrikeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //GameAdapterFactory
