/*
 * European Scoring Tool For Baseball
 * Copyright (C) 2020  Patrick BRIAND
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * generated by Xtext 2.23.0
 */
package org.bpy.score.game.ui.outline;

import org.bpy.score.engine.util.EngineConstants;
import org.bpy.score.game.game.Actions;
import org.bpy.score.game.game.Game;
import org.bpy.score.game.game.GameResume;
import org.bpy.score.game.game.HalfInning;
import org.bpy.score.game.game.LineUp;
import org.bpy.score.game.game.Player;
import org.bpy.score.game.game.Roster;
import org.bpy.score.internationalization.game.Messages;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.osgi.util.NLS;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class GameOutlineTreeProvider extends DefaultOutlineTreeProvider {

	@Override
	public void _createChildren(IOutlineNode parentNode, EObject parentModelElement) {

		if (parentModelElement instanceof Game) {
			Game game = (Game) parentModelElement;
			
			if (game.getHometeam() != null) {
				createNode(parentNode, game.getHometeam());
			}
			
			if (game.getVisitor() != null) {
				createNode(parentNode, game.getVisitor());
			}
			
			if (game.getActions() != null) {
				createNode(parentNode, game.getActions());
			}
		
		} else if (parentModelElement instanceof Roster) {
			Roster roster = (Roster) parentModelElement;
			for (Player player : roster.getPlayers()) {
				createNode(parentNode, player);
			}
		
		} else if (parentModelElement instanceof Actions) {
			Actions actions = (Actions) parentModelElement;
			
			if (actions.getLineup() != null) {
				for ( LineUp lineup : actions.getLineup()) {
					createNode(parentNode, lineup);
				}
			}

			if (actions.getHalfInnings() != null) {
				for (HalfInning halfInning : actions.getHalfInnings()) {
					createNode(parentNode, halfInning);
				}
			}
			
			if (actions.getGameResume() != null) {
				createNode(parentNode, actions.getGameResume());
			}
		}
	}	

	/**
	 * Set game resume names 
	 * 
	 * @param gameResume reference on the GameResume rule
	 * 
	 * @return Displayed constant name 
	 */
	@SuppressWarnings("java:S100")
	public Object _text(GameResume gameResume) {
		return Messages.GameOutlineTreeProvider_GameResume;
	}
	
	/**
	 * Set half Innning names 
	 * 
	 * @param halfInnning reference on the HalfInnning rule
	 * 
	 * @return Displayed constant name 
	 */
	@SuppressWarnings("java:S100")
	public Object _text(HalfInning halfInnning) {
		
		if (halfInnning.getTeam().equals(EngineConstants.VISITOR)) {
			return NLS.bind(Messages.GameOutlineTreeProvider_HalfInningVisitor, halfInnning.getNumber());
		} else {
			return NLS.bind(Messages.GameOutlineTreeProvider_HalfInningHometeam, halfInnning.getNumber());
		}
	}
	
	/**
	 * Set line-up names 
	 * 
	 * @param lineup reference on the Lineup rule
	 * 
	 * @return Displayed name 
	 */
	@SuppressWarnings("java:S100")
	public Object _text(LineUp lineup) {
		if (lineup.getTeamType().equals(EngineConstants.VISITOR)) {
			return Messages.GameOutlineTreeProvider_LineupVisitor;
		} else {
			return Messages.GameOutlineTreeProvider_LineupHometeam;
		}
	}
	
	
	/**
	 * Set Roster names 
	 * 
	 * @param roster reference on the roster rule
	 * 
	 * @return Displayed name 
	 */
	@SuppressWarnings("java:S100")
	public Object _text(Roster roster) {
		if (roster.getWho().equals(EngineConstants.VISITOR)) {
			return NLS.bind(Messages.GameOutlineTreeProvider_RosterVisitor, new Object[] {roster.getName()});
		} else {
			return NLS.bind(Messages.GameOutlineTreeProvider_RosterHometeam, new Object[] {roster.getName()});
		}
	}

	/**
	 * Set Roster names 
	 * 
	 * @param actions reference on the actions rule
	 * 
	 * @return Displayed constant name 
	 */
	@SuppressWarnings("java:S100")
	public Object _text(Actions actions) {
		return Messages.GameOutlineTreeProvider_GameDescription;
	}
}
