<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>org.bpy.score.help</artifactId>
	<packaging>eclipse-plugin</packaging>

	<parent>
		<groupId>org.bpy.score</groupId>
		<artifactId>org.bpy.score.parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../org.bpy.score.build/parent/pom.xml</relativePath>
	</parent>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>Clean help directories</id>
						<phase>install</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<delete
									dir="${project.basedir}/nl/en/Scorers_manual"
									includeEmptyDirs="true" failonerror="false" />
								<delete
									dir="${project.basedir}/nl/en/User_manual"
									includeEmptyDirs="true" failonerror="false" />
								<delete
									dir="${project.basedir}/nl/fr/Scorers_manual"
									includeEmptyDirs="true" failonerror="false" />
								<delete
									dir="${project.basedir}/nl/fr/User_manual"
									includeEmptyDirs="true" failonerror="false" />
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>Generate english help</id>
						<phase>install</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>cmd.exe</executable>
							<arguments>
								<argument>/c</argument>
								<argument>java</argument>
								<argument>-jar</argument>
								<!-- Chemin vers votre JAR -->
								<argument>
									${project.basedir}/HelpGenerator.jar</argument>
								<argument>doc/english</argument>
								<argument>nl/en</argument>
							</arguments>
							<workingDirectory>${basedir}</workingDirectory>
						</configuration>
					</execution>
					<execution>
						<id>Generate french help</id>
						<phase>install</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>cmd.exe</executable>
							<arguments>
								<argument>/c</argument>
								<argument>java</argument>
								<argument>-jar</argument>
								<!-- Chemin vers votre JAR -->
								<argument>
									${project.basedir}/HelpGenerator.jar</argument>
								<argument>doc/french</argument>
								<argument>nl/fr</argument>
							</arguments>
							<workingDirectory>${basedir}</workingDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

</project>